#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/ai-alternatives",
  "--title",
  "What AI alternatives we have",
  "--topic",
  "AI alternatives",
  "--output-id",
  "ai-alternatives",
  "--pattern",
  "comparison-matrix",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "The named alternatives map to different home bases for AI work.",
  "--fact",
  "Atlassian Rovo is strongest for organizational knowledge across Jira, Confluence, and connected tools.",
  "--fact",
  "Gemini App is a consumer and prosumer assistant with subscription tiers and deep Google ecosystem ties.",
  "--fact",
  "GitHub Copilot is strongest as a coding harness inside developer workflows.",
  "--fact",
  "Claude Desktop and Claude Code are strong for coding and research workflows with connectors, skills, hooks, plugins, and MCP.",
  "--fact",
  "Rovo ships in paid Atlassian cloud subscriptions and Rovo Dev uses a credit model per developer.",
  "--fact",
  "Copilot has Free through Enterprise plans and AI-credit billing.",
  "--fact",
  "Claude blends subscriptions with API-style usage, while Gemini uses plan tiers and region-dependent availability.",
  "--anchor",
  "comparison grid",
  "--anchor",
  "Atlassian suite knowledge graph feeding Rovo",
  "--anchor",
  "Gemini plan cards",
  "--anchor",
  "Copilot runtime stack",
  "--anchor",
  "Claude desktop to terminal transition",
  "--anchor",
  "use-case quadrants",
  "--anchor",
  "four cost meters",
  "--anchor",
  "choose by workflow gravity selector",
  "--option-label",
  "Rovo",
  "--option-label",
  "Gemini App",
  "--option-label",
  "GitHub Copilot",
  "--option-label",
  "Claude Desktop/Code",
  "--criterion-label",
  "Knowledge home",
  "--criterion-label",
  "Coding workflow",
  "--criterion-label",
  "Extensibility",
  "--criterion-label",
  "Budget model",
  "--criterion-label",
  "Permissions",
  "--criterion-label",
  "Observability",
  "--criterion-label",
  "Workflow gravity",
  "--criterion-label",
  "Plan tiers"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
