#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-render-state-stub-validation/fresh-systems-flow",
  "--title",
  "Metro Stub Validation",
  "--topic",
  "Render state stub",
  "--output-id",
  "metro-stub-validation",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "4.0",
  "--fps",
  "12",
  "--width",
  "640",
  "--height",
  "360",
  "--edge-style",
  "square",
  "--fact",
  "A render-state checker must sample square-edge Metro HTML without requiring a browser fallback.",
  "--anchor",
  "square edge state probe",
  "--system-label",
  "Source",
  "--system-label",
  "Queue",
  "--system-label",
  "Worker",
  "--system-label",
  "Control",
  "--system-label",
  "bounded queue",
  "--system-label",
  "worker pool",
  "--system-label",
  "DB",
  "--system-label",
  "retry policy",
  "--system-label",
  "dead-letter",
  "--system-label",
  "throughput",
  "--system-label",
  "throttle"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
