#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-an-mcp",
  "--title",
  "What is an MCP",
  "--topic",
  "What is an MCP",
  "--output-id",
  "what-is-an-mcp",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "MCP stands for Model Context Protocol.",
  "--fact",
  "MCP is an open standard for connecting AI clients to external systems such as tools, resources, and prompts.",
  "--fact",
  "MCP gives clients and servers a shared protocol instead of requiring one custom integration per assistant.",
  "--fact",
  "An MCP server can expose tools, resources, and prompts.",
  "--fact",
  "MCP is supported across major clients including Claude, ChatGPT-related ecosystems, VS Code, and GitHub Copilot.",
  "--fact",
  "Authentication and authorization matter because MCP can expose real systems.",
  "--fact",
  "Registries, allowlists, and approval policies help govern MCP access.",
  "--fact",
  "MCP can affect cost because tool discovery, tool descriptions, tool calls, and downstream APIs add context or external spend.",
  "--anchor",
  "MCP bus",
  "--anchor",
  "messy point-to-point integrations becoming one protocol bus",
  "--anchor",
  "tools resources prompts lanes",
  "--anchor",
  "neutral client cards",
  "--anchor",
  "lock icons on bus",
  "--anchor",
  "registry gate",
  "--anchor",
  "approval shield",
  "--anchor",
  "context meter and external billing icons",
  "--system-label",
  "Client",
  "--system-label",
  "MCP bus",
  "--system-label",
  "Tools",
  "--system-label",
  "Resources",
  "--system-label",
  "Prompts",
  "--system-label",
  "Auth",
  "--system-label",
  "Registry",
  "--system-label",
  "Approval",
  "--system-label",
  "Downstream API",
  "--system-label",
  "Cost/context",
  "--system-label",
  "Read data",
  "--system-label",
  "Execute action",
  "--system-label",
  "Structured workflow",
  "--system-label",
  "Least privilege"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
