#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from plantuml_coverage import load_manifest, validate_report_coverage


COLORSET_TOKENS = {
    "colorset1": {
        "#9E1B32",
        "#6D1222",
        "#E8002A",
        "#FFCCD5",
        "#333E48",
        "#696969",
        "#9C9C9C",
        "#CFCFCF",
        "#E7E7E7",
        "#FFFFFF",
        "#000000",
    },
    "colorset2": {
        "#9E1B32",
        "#007298",
        "#E77204",
        "#45842A",
        "#00ACE6",
        "#652F6C",
        "#333E48",
        "#696969",
        "#FFCCD5",
        "#CDF3FF",
        "#FFE5CC",
        "#DBFFCC",
        "#F9CCFF",
    },
}
STYLE_PROOF_TOKENS = {
    colorset: tokens - {"#FFFFFF", "#000000"}
    for colorset, tokens in COLORSET_TOKENS.items()
}
DISTINCTIVE_REPORT_TOKENS = {
    "colorset1": {"#9E1B32", "#6D1222", "#E8002A", "#FFCCD5"},
    "colorset2": {"#9E1B32", "#007298", "#E77204", "#45842A", "#00ACE6", "#652F6C", "#FFCCD5", "#CDF3FF", "#FFE5CC", "#DBFFCC", "#F9CCFF"},
}


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate a PlantUML render report and rendered artifacts.")
    parser.add_argument("--report", type=Path, required=True, help="Report generated by render_plantuml_directory.py.")
    parser.add_argument("--output", type=Path, required=True, help="Render output directory used for the report.")
    parser.add_argument("--expected-diagrams", type=int, help="Expected rendered diagram count.")
    parser.add_argument("--expect-format", action="append", choices=["svg", "png"], default=[], help="Required output format. May be repeated.")
    parser.add_argument("--colorset", choices=sorted(COLORSET_TOKENS), default="colorset2", help="Expected bundled colorset palette.")
    parser.add_argument("--coverage-manifest", type=Path, help="Require exact family and fixture coverage from the frozen manifest.")
    args = parser.parse_args()

    report = load_json(args.report)
    output_dir = args.output
    findings: list[str] = []

    if report.get("ok") is not True:
        findings.append("report ok must be true")
    if report.get("failedDiagramCount") != 0:
        findings.append("failedDiagramCount must be 0")
    if args.expected_diagrams is not None and report.get("renderedDiagramCount") != args.expected_diagrams:
        findings.append(f"renderedDiagramCount must be {args.expected_diagrams}")
    if report.get("colorset") not in {None, args.colorset}:
        findings.append(f"report colorset must be {args.colorset}")
    if args.coverage_manifest:
        findings.extend(validate_report_coverage(report, load_manifest(args.coverage_manifest)))

    expected_formats = set(args.expect_format or report.get("formats") or [])
    results = report.get("results")
    if not isinstance(results, list) or not results:
        findings.append("report results must be a non-empty list")
        results = []

    seen_svg_tokens: set[str] = set()
    requires_svg_palette = False
    expected_tokens = COLORSET_TOKENS[args.colorset]
    style_proof_tokens = STYLE_PROOF_TOKENS[args.colorset]
    for result in results:
        if not isinstance(result, dict):
            findings.append("each result must be an object")
            continue
        outputs = result.get("outputs")
        if not isinstance(outputs, list):
            findings.append(f"{result.get('source')}: outputs must be a list")
            continue
        formats = {output.get("format") for output in outputs if isinstance(output, dict)}
        result_expected_formats = result.get("expectedFormats")
        required_formats = (
            set(result_expected_formats)
            if isinstance(result_expected_formats, list)
            else expected_formats
        )
        missing_formats = required_formats - formats
        if missing_formats:
            findings.append(f"{result.get('source')}: missing formats {sorted(missing_formats)}")
        unexpected_formats = formats - required_formats
        if result_expected_formats is not None and unexpected_formats:
            findings.append(f"{result.get('source')}: unexpected formats {sorted(unexpected_formats)}")
        result_svg_tokens: set[str] = set()
        if result.get("themeMode") == "inject" and result.get("themeApplied") is not True:
            findings.append(f"{result.get('source')}: inject themeMode requires themeApplied=true")
        if result.get("themeMode") == "none" and result.get("themeApplied") is not False:
            findings.append(f"{result.get('source')}: none themeMode requires themeApplied=false")
        for output in outputs:
            if not isinstance(output, dict):
                findings.append(f"{result.get('source')}: output must be an object")
                continue
            relative_path = output.get("path")
            fmt = output.get("format")
            if not isinstance(relative_path, str) or not isinstance(fmt, str):
                findings.append(f"{result.get('source')}: output path and format must be strings")
                continue
            artifact = output_dir / relative_path
            if not artifact.is_file() or artifact.stat().st_size <= 0:
                findings.append(f"{result.get('source')}: missing or empty artifact {relative_path}")
                continue
            if fmt == "svg":
                text = artifact.read_text(encoding="utf-8", errors="replace")
                if "<svg" not in text:
                    findings.append(f"{relative_path}: missing <svg")
                uppercase = text.upper()
                tokens = {token for token in expected_tokens if token in uppercase}
                result_svg_tokens.update(tokens)
                seen_svg_tokens.update(tokens)
            if fmt == "png" and not artifact.read_bytes().startswith(b"\x89PNG\r\n\x1a\n"):
                findings.append(f"{relative_path}: invalid PNG signature")
        if result.get("themeApplied") is True and "svg" in required_formats:
            requires_svg_palette = True
        if result.get("themeApplied") is True and "svg" in required_formats and not (result_svg_tokens & style_proof_tokens):
            findings.append(f"{result.get('source')}: themed SVG must contain a {args.colorset} color token")

    if requires_svg_palette and not (seen_svg_tokens & DISTINCTIVE_REPORT_TOKENS[args.colorset]):
        findings.append(f"SVG outputs must contain at least one distinctive {args.colorset} color token")

    validation = {
        "ok": not findings,
        "colorset": args.colorset,
        "checkedDiagramCount": len(results),
        "expectedFormats": sorted(expected_formats),
        "seenSvgColorTokens": sorted(seen_svg_tokens),
        "findings": findings,
    }
    print(json.dumps(validation, indent=2))
    return 0 if validation["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
