#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


COLORSET_TOKENS = {
    "colorset1": {
        "#9E1B32",
        "#6D1222",
        "#E8002A",
        "#FFCCD5",
        "#333E48",
        "#696969",
        "#9C9C9C",
        "#CFCFCF",
        "#E7E7E7",
        "#FFFFFF",
        "#000000",
    },
    "colorset2": {
        "#9E1B32",
        "#007298",
        "#E77204",
        "#45842A",
        "#00ACE6",
        "#652F6C",
        "#333E48",
        "#696969",
        "#FFCCD5",
        "#CDF3FF",
        "#FFE5CC",
        "#DBFFCC",
        "#F9CCFF",
    },
}


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate a PlantUML render report and rendered artifacts.")
    parser.add_argument("--report", type=Path, required=True, help="Report generated by render_plantuml_directory.py.")
    parser.add_argument("--output", type=Path, required=True, help="Render output directory used for the report.")
    parser.add_argument("--expected-diagrams", type=int, help="Expected rendered diagram count.")
    parser.add_argument("--expect-format", action="append", choices=["svg", "png"], default=[], help="Required output format. May be repeated.")
    parser.add_argument("--colorset", choices=sorted(COLORSET_TOKENS), default="colorset2", help="Expected bundled colorset palette.")
    args = parser.parse_args()

    report = load_json(args.report)
    output_dir = args.output
    findings: list[str] = []

    if report.get("ok") is not True:
        findings.append("report ok must be true")
    if report.get("failedDiagramCount") != 0:
        findings.append("failedDiagramCount must be 0")
    if args.expected_diagrams is not None and report.get("renderedDiagramCount") != args.expected_diagrams:
        findings.append(f"renderedDiagramCount must be {args.expected_diagrams}")
    if report.get("colorset") not in {None, args.colorset}:
        findings.append(f"report colorset must be {args.colorset}")

    expected_formats = set(args.expect_format or report.get("formats") or [])
    results = report.get("results")
    if not isinstance(results, list) or not results:
        findings.append("report results must be a non-empty list")
        results = []

    seen_svg_tokens: set[str] = set()
    expected_tokens = COLORSET_TOKENS[args.colorset]
    for result in results:
        if not isinstance(result, dict):
            findings.append("each result must be an object")
            continue
        outputs = result.get("outputs")
        if not isinstance(outputs, list):
            findings.append(f"{result.get('source')}: outputs must be a list")
            continue
        formats = {output.get("format") for output in outputs if isinstance(output, dict)}
        missing_formats = expected_formats - formats
        if missing_formats:
            findings.append(f"{result.get('source')}: missing formats {sorted(missing_formats)}")
        for output in outputs:
            if not isinstance(output, dict):
                findings.append(f"{result.get('source')}: output must be an object")
                continue
            relative_path = output.get("path")
            fmt = output.get("format")
            if not isinstance(relative_path, str) or not isinstance(fmt, str):
                findings.append(f"{result.get('source')}: output path and format must be strings")
                continue
            artifact = output_dir / relative_path
            if not artifact.is_file() or artifact.stat().st_size <= 0:
                findings.append(f"{result.get('source')}: missing or empty artifact {relative_path}")
                continue
            if fmt == "svg":
                text = artifact.read_text(encoding="utf-8", errors="replace")
                if "<svg" not in text:
                    findings.append(f"{relative_path}: missing <svg")
                uppercase = text.upper()
                seen_svg_tokens.update(token for token in expected_tokens if token in uppercase)
            if fmt == "png" and not artifact.read_bytes().startswith(b"\x89PNG\r\n\x1a\n"):
                findings.append(f"{relative_path}: invalid PNG signature")

    if not seen_svg_tokens:
        findings.append(f"SVG outputs must contain at least one {args.colorset} color token")

    validation = {
        "ok": not findings,
        "colorset": args.colorset,
        "checkedDiagramCount": len(results),
        "expectedFormats": sorted(expected_formats),
        "seenSvgColorTokens": sorted(seen_svg_tokens),
        "findings": findings,
    }
    print(json.dumps(validation, indent=2))
    return 0 if validation["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
