#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-semantic-density-video",
  "--title",
  "Metro Semantic Density Validation",
  "--topic",
  "semantic-density proof for Metro video-generation skill validation",
  "--output-id",
  "metro-semantic-density",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "6.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "The video must show a navigable modular megacanvas rather than labeled slides.",
  "--fact",
  "Camera movement must be visible through render-state diversity.",
  "--fact",
  "Camera movement must show meaningful travel and zoom depth, not tiny decorative nudges.",
  "--fact",
  "Queue fill, retry, dead-letter, and feedback throttle must all appear as late mechanisms.",
  "--fact",
  "Contact-sheet frames must change enough to prove visual progression.",
  "--fact",
  "Hiding all SVG text must still leave enough visible mark motion, zones, gray hierarchy, and nonbackground area for the mute test to pass.",
  "--fact",
  "The semantic-density audit must show a continuity path through zones, not only distinct state-summary values.",
  "--fact",
  "The semantic-density audit must prove every visual anchor is bound through source package, rendered DOM, and render-state evidence.",
  "--fact",
  "The semantic-density audit must pass after the wrapper, state check, contact sheet, Metro audit suite, mute-test audit, and encoded-MP4 composition audit.",
  "--anchor",
  "modular megacanvas",
  "--anchor",
  "semantic density",
  "--anchor",
  "queue fill",
  "--anchor",
  "retry branch",
  "--anchor",
  "dead-letter branch",
  "--anchor",
  "feedback throttle",
  "--anchor",
  "camera exploration",
  "--anchor",
  "contact-sheet progression",
  "--system-label",
  "Gateway",
  "--system-label",
  "Event bus",
  "--system-label",
  "Queue",
  "--system-label",
  "Worker pool",
  "--system-label",
  "Retry policy",
  "--system-label",
  "Dead letter",
  "--system-label",
  "Metrics",
  "--system-label",
  "Throttle",
  "--system-label",
  "dead-letter",
  "--system-label",
  "throughput",
  "--system-label",
  "throttle"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
