#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/llm-billing",
  "--title",
  "LLM Billing",
  "--topic",
  "LLM Billing",
  "--output-id",
  "llm-billing",
  "--pattern",
  "metric-dashboard",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "LLM billing reduces to model selected, input tokens, output tokens, and whether usage is wrapped in a subscription.",
  "--fact",
  "GitHub Copilot meters usage in AI credits, where 1 AI credit equals $0.01.",
  "--fact",
  "Token usage converts into credits based on the selected model.",
  "--fact",
  "Copilot Pro includes 1,500 AI credits per month, and Business includes 1,900 credits per seat in a pooled organization bucket.",
  "--fact",
  "Claude API pricing is direct per million input, cached-input, and output tokens.",
  "--fact",
  "Claude subscriptions package the underlying usage instead of removing the usage cost.",
  "--fact",
  "Local models are not free because electricity, hardware life, and developer time still have costs.",
  "--fact",
  "Better prompts, smaller sufficient models, hooks, and skills usually reduce wasted retries and cost.",
  "--anchor",
  "credit meter",
  "--anchor",
  "token stream converting into dollars or credits",
  "--anchor",
  "individual versus pooled bucket split",
  "--anchor",
  "Claude pricing table cards",
  "--anchor",
  "subscription layers over raw token meter",
  "--anchor",
  "GPU rack with power meter and clock",
  "--anchor",
  "retry spiral",
  "--anchor",
  "optimized cost waterfall",
  "--anchor",
  "final cost scorecard",
  "--metric-label",
  "selected model",
  "--metric-label",
  "input tokens",
  "--metric-label",
  "output tokens",
  "--metric-label",
  "AI credits",
  "--metric-label",
  "cached input",
  "--metric-label",
  "subscription allowance",
  "--metric-label",
  "local electricity",
  "--metric-label",
  "hardware amortization",
  "--metric-label",
  "developer time",
  "--metric-label",
  "retry waste",
  "--threshold-label",
  "1 AI credit = $0.01",
  "--threshold-label",
  "Pro 1,500 credits/month",
  "--threshold-label",
  "Business 1,900 credits/seat",
  "--threshold-label",
  "60 AI credits example",
  "--threshold-label",
  "Claude per million tokens",
  "--threshold-label",
  "local is not free",
  "--threshold-label",
  "fewer wasted loops"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
