#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Build an offline five-poster gallery with searchable sources and comparisons."""
from pathlib import Path
import html
import json
import shutil
import zipfile

ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1];OUT=ROOT/'artifacts'
CASES=[
 dict(id='instruments',title='How instruments make sound',meta='71 categories · 66 connections · 15 illustrated examples',description='Find what vibrates. Compare a handbell, a kazoo, a harp and an electronic signal.',challenge=[('Why is a kazoo here?','242'),('Find the plucked tongue','122'),('Follow a software instrument','56')],before=REPO/'projects/usefulcharts-cross-domain/artifacts/revision-2/instruments/poster.png'),
 dict(id='starships',title='Star Trek: the fleet through time',meta='79 ships · 14 shared tracks · 7 large views + 12 trail images',description='Read recognizable silhouettes, follow their dated wakes and compare names with physical hulls.',challenge=[('Find a known launch','enterprise-nx'),('Compare the Defiant hulls','defiant-second'),('Follow Voyager home','voyager')],before=REPO/'projects/star-trek-starships/artifacts/flow-edition/images/star-trek-starships-preview.png'),
 dict(id='mars',title='The long road to Mars',meta='32 launch campaigns · 52 date marks · 7 spacecraft images',description='Explore an orbiter and a lander, then trace their separate journeys on a shared calendar.',challenge=[('Trace two Viking vehicles','viking1'),('Find the failed orbit insertion','nozomi'),('Five probes, one campaign','mars96')],before=REPO/'projects/usefulcharts-cross-domain/artifacts/revision-2/mars/poster.png'),
 dict(id='bsd',title='UNIX and the BSD family',meta='47 releases · 51 relationships · 6 illustrated scenes',description='Follow shared code from a terminal to several branches, with period-inspired machines along the way.',challenge=[('Trace the arrival of pipes','v3'),('One source, three paths','lite'),('Find the desktop branch','386a')],before=REPO/'projects/usefulcharts-cross-domain/artifacts/revision-2/bsd/poster.png'),
 dict(id='civilizations',title='Star Trek: civilizations and wars',meta='155 historical entries · 10 integrated illustrations',description='Meet the civilizations, follow changing alliances and keep alternate histories distinct.',challenge=[('Follow First Contact','st-001'),('Watch the Dominion alliance form','st-076'),('Compare the Borg stories','st-116')],before=REPO/'projects/star-trek-canonical-timeline/artifacts/images/star-trek-preview.png'),
]

VIEWER=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1721;color:#eaf1ef;font:15px system-ui,Arial}button,input,a.pill{font:inherit;border:1px solid #536876;background:#172c3a;color:inherit;border-radius:7px;padding:9px 12px}button,a{cursor:pointer}button:hover,a.pill:hover{background:#2c485a}a{color:#a6dded}header{height:70px;display:flex;align-items:center;gap:9px;padding:12px 20px;border-bottom:1px solid #39505f}header strong{margin-right:auto;font-size:17px}#stage{position:absolute;inset:70px 315px 0 0;overflow:auto;padding:24px}#paper{margin:auto;position:relative}#paper>svg,#before{display:block;width:100%;height:auto}#before{display:none}aside{position:absolute;right:0;top:70px;bottom:0;width:315px;padding:24px;overflow:auto;background:#112330;border-left:1px solid #3b5464}h1{font-size:25px;line-height:1.1}p{line-height:1.55}.muted{color:#aac0cb;font-size:13px}#search{width:100%;margin:10px 0}#results button,#quests button{display:block;width:100%;text-align:left;margin:7px 0;font-size:13px}#results button{background:#1b3444}#sources a{display:block;margin:10px 0;overflow-wrap:anywhere}#links{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.pill{text-decoration:none;font-size:13px!important;padding:8px!important}.focus-box{fill:none;stroke:#ffdc85;stroke-width:6;pointer-events:none}g[data-record-id],g.record,g[data-id]{cursor:pointer}#mobile-info{display:none}hr{border:0;border-top:1px solid #385362;margin:24px 0}#zoom{font-size:13px;min-width:38px}@media(max-width:1000px){header strong{display:none}header{padding:9px}#stage{right:280px}aside{width:280px;padding:16px}}@media(max-width:720px){#stage{right:0;padding:10px}aside{display:none;width:min(90vw,360px);z-index:4;box-shadow:-12px 0 30px #0008}aside.open{display:block}#mobile-info{display:block}header{gap:5px}header button{padding:8px}.gallery-link{font-size:12px}#zoom{display:none}}
</style><header><a class="gallery-link" href="../../gallery/index.html">← Gallery</a><strong>__TITLE__</strong><button id="fit">Fit</button><button id="read">Read</button><button id="minus" aria-label="Zoom out">−</button><span id="zoom"></span><button id="plus" aria-label="Zoom in">+</button><button id="compare">Before</button><button id="mobile-info">Explore</button></header><main id="stage"><div id="paper">__SVG__<img id="before" src="before.png" alt="Previous text-focused composition"></div></main><aside id="info"><h1>__TITLE__</h1><p class="muted">__META__</p><p>__DESCRIPTION__</p><div id="quests">__QUESTS__</div><input id="search" type="search" placeholder="Find a name, date or subject" aria-label="Search records"><div id="results"></div><hr><h2 id="record-title">Explore a record</h2><p id="record-date" class="muted"></p><p id="record-detail">Select a record or a question to inspect its complete source notes.</p><p id="record-credit" class="muted"></p><div id="sources"></div><div id="links"><a class="pill" href="poster.svg" download>SVG</a><a class="pill" href="poster.pdf" download>PDF</a><a class="pill" href="poster.png" download>PNG</a><a class="pill" href="source.json" download>Data</a></div><p class="muted">Illustrations, photographs and period archetypes are identified in the poster and artwork manifest. The selected information is retained. A measured UsefulCharts density comparison remains pending.</p></aside><script>
const items=__RECORDS__,byId=new Map(items.map(n=>[n.id,n])),stage=document.querySelector('#stage'),paper=document.querySelector('#paper'),svg=paper.querySelector(':scope > svg'),before=document.querySelector('#before');let scale=1,comparison=false;const width=+svg.getAttribute('width');
function zoom(value){scale=Math.max(.09,Math.min(2,value));paper.style.width=width*scale+'px';document.querySelector('#zoom').textContent=Math.round(scale*100)+'%'}
function fit(){zoom((stage.clientWidth-48)/width)}document.querySelector('#fit').onclick=fit;document.querySelector('#read').onclick=()=>zoom(1);document.querySelector('#minus').onclick=()=>zoom(scale/1.35);document.querySelector('#plus').onclick=()=>zoom(scale*1.35);
document.querySelector('#compare').onclick=()=>{comparison=!comparison;svg.style.display=comparison?'none':'block';before.style.display=comparison?'block':'none';document.querySelector('#compare').textContent=comparison?'After':'Before'};
document.querySelector('#mobile-info').onclick=()=>document.querySelector('#info').classList.toggle('open');
function element(id){return [...svg.querySelectorAll('[data-record-id],g.record,[data-id]')].find(e=>(e.dataset.recordId||e.dataset.id||e.id)===id)}
function select(id,move=true){const item=byId.get(id);if(!item)return;document.querySelector('#record-title').textContent=item.title;document.querySelector('#record-date').textContent=item.date||'';document.querySelector('#record-detail').textContent=item.detail||'';document.querySelector('#record-credit').textContent=item.credit||'';const sources=document.querySelector('#sources');sources.replaceChildren();for(const source of item.sources){const a=document.createElement('a');a.href=source.url;a.textContent=source.title;a.target='_blank';a.rel='noopener';sources.append(a)}
svg.querySelectorAll('.focus-box').forEach(e=>e.remove());const e=element(id);if(e){const b=e.getBBox(),r=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [k,v] of Object.entries({x:b.x-8,y:b.y-8,width:b.width+16,height:b.height+16,class:'focus-box'}))r.setAttribute(k,v);svg.append(r);if(move){if(comparison)document.querySelector('#compare').click();zoom(Math.max(scale,.7));const a=e.getBoundingClientRect(),s=stage.getBoundingClientRect();stage.scrollBy({left:a.left-s.left-stage.clientWidth*.2,top:a.top-s.top-60,behavior:'instant'})}}}
svg.addEventListener('click',ev=>{const e=ev.target.closest('[data-record-id],g.record,[data-id],[data-art-anchor]');if(e)select(e.dataset.recordId||e.dataset.id||e.dataset.artAnchor?.split(' ')[0]||e.id,false)});
document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>select(b.dataset.focus));document.querySelector('#search').addEventListener('input',ev=>{const value=ev.target.value.toLowerCase().trim(),result=document.querySelector('#results');result.replaceChildren();if(!value)return;for(const n of items.filter(n=>JSON.stringify(n).toLowerCase().includes(value)).slice(0,15)){const b=document.createElement('button');b.textContent=n.title+' · '+n.date;b.onclick=()=>select(n.id);result.append(b)}});window.addEventListener('resize',()=>{if(scale<.5)fit()});fit();
</script></html>'''

def records(source):
    nodes=source.get('nodes') or source.get('ships') or [n for k in ['events','origins','future','branches'] for n in source.get(k,[])]
    result=[]
    for n in nodes:
        ref=source.get('sources',{}).get(n.get('source'),{}) if isinstance(source.get('sources',{}),dict) else {}
        url=n.get('source_url') or ref.get('url');links=[dict(url=url,title=ref.get('title','Source reference'))] if url else []
        date=n.get('date_label') or n.get('date') or n.get('code') or ('Launch '+str(n['launch']) if n.get('launch') else 'Construction or launch date not established')
        detail=n.get('detail') or n.get('note','')
        if 'design' in n:detail=n['design']+' · '+n.get('registry','')+' · '+n.get('operator','')+'. '+detail
        if n.get('qualifier'):detail+=' '+n['qualifier']
        result.append(dict(id=n['id'],title=n.get('label',n.get('name',n['id'])),date=str(date),detail=detail,credit=n.get('credit',''),sources=links))
    return result

def main():
    gallery=OUT/'gallery';gallery.mkdir(parents=True,exist_ok=True);cards=[]
    for c in CASES:
        path=OUT/'revision-2'/c['id'];shutil.copy2(c['before'],path/'before.png')
        data=json.loads((path/'source.json').read_text(encoding='utf-8'));svg=(path/'poster.svg').read_text(encoding='utf-8')
        result=VIEWER
        substitutions={'TITLE':html.escape(c['title']),'META':html.escape(c['meta']),'DESCRIPTION':html.escape(c['description']),'QUESTS':''.join(f'<button data-focus="{i}">{html.escape(t)} →</button>' for t,i in c['challenge']),'SVG':svg,'RECORDS':json.dumps(records(data),ensure_ascii=False).replace('</',r'<\/')}
        for key,value in substitutions.items():result=result.replace('__'+key+'__',value)
        (path/'poster.html').write_text(result,encoding='utf-8')
        cards.append(f'<article data-diagram-id="{c["id"]}"><a class="preview" href="../revision-2/{c["id"]}/poster.html"><img src="../revision-2/{c["id"]}/preview.png" alt="{html.escape(c["title"])}"></a><div class="body"><p class="eyebrow">{html.escape(c["meta"])}</p><h2>{html.escape(c["title"])}</h2><p>{html.escape(c["description"])}</p><div class="actions"><a href="../revision-2/{c["id"]}/poster.html">Explore the diagram →</a><a href="../revision-2/{c["id"]}/poster.pdf">PDF</a><a href="../revision-2/{c["id"]}/poster.svg">SVG</a></div></div></article>')
    gallery_html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Illustrated discovery · Five field guides</title><style>*{box-sizing:border-box}body{margin:0;background:#f4efe4;color:#16303c;font:17px system-ui,Arial}header{background:#102937;color:#f7f1e4;padding:55px max(5vw,24px)}header p{max-width:850px;line-height:1.65;color:#c6dce4}h1{font-size:clamp(34px,5vw,68px);line-height:1.02;max-width:900px;margin:16px 0 25px}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:12px;font-weight:700;color:#506a73}.tag{color:#eccb85;letter-spacing:.16em;font-size:13px;text-transform:uppercase}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px;padding:36px max(5vw,24px);max-width:1600px;margin:auto}article{background:#fffaf0;border:1px solid #d6d3c9;border-radius:18px;overflow:hidden;box-shadow:0 8px 30px #25372b09}.preview{display:block;height:370px;background:#122535;overflow:hidden}.preview img{width:100%;height:100%;object-fit:cover;object-position:top;transition:transform .25s}.preview:hover img{transform:scale(1.025)}.body{padding:24px}h2{font-size:26px;line-height:1.12;margin:12px 0}p{line-height:1.6}.actions{display:flex;gap:22px;flex-wrap:wrap;margin-top:22px}a{color:#18536c;font-weight:650}footer{padding:20px max(5vw,24px) 60px;max-width:1500px;margin:auto;font-size:14px;color:#4b666d}footer a{color:#18536c}@media(max-width:760px){.grid{grid-template-columns:1fr;gap:22px;padding:24px 16px}.preview{height:310px}header{padding:34px 22px}.body{padding:20px}}</style><header><div class="tag">Five illustrated field guides</div><h1>More to see.<br>More to discover.</h1><p>Trace a ship through time, compare the parts of an instrument, follow shared code or watch an alliance change. Every poster keeps its selected records and gives you images, questions and source notes to explore.</p></header><main class="grid">'''+''.join(cards)+'''</main><footer><p>Open a diagram to zoom, search records, follow a discovery question or compare the previous version. SVG, PDF and PNG downloads work offline. Spacecraft and Mars dates retain their original x coordinates; the family charts and civilization branches declare their schematic spacing.</p><p><a href="../illustrated-diagrams.zip">Download all five diagrams</a> · <a href="../reviews/visual-review.md">Read the critique and validation notes</a></p><p>Independent educational design study. Image-assisted artwork is distinguished from source photographs. Reference-density parity with UsefulCharts has not been established.</p></footer></html>'''
    (gallery/'index.html').write_text(gallery_html,encoding='utf-8')
    with zipfile.ZipFile(OUT/'illustrated-diagrams.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
        archive.writestr('gallery/index.html',gallery_html.replace('<a href="../illustrated-diagrams.zip">Download all five diagrams</a> · ',''))
        for c in CASES:
            path=OUT/'revision-2'/c['id']
            for name in ['poster.html','poster.svg','poster.pdf','poster.png','preview.png','before.png','source.json','art-map.json']:
                archive.write(path/name,f'revision-2/{c["id"]}/{name}')
        for name in ['visual-review.md','independent-checks.json']:
            file=OUT/'reviews'/name
            if file.exists():archive.write(file,'reviews/'+name)
    print(json.dumps(dict(diagrams=len(CASES),archive_bytes=(OUT/'illustrated-diagrams.zip').stat().st_size)))
if __name__=='__main__':main()
