#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Record the completed direct whole/detail/PDF reviews and their evidence hashes."""
from pathlib import Path
import hashlib
import json
import sys
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
sys.path.insert(0,str(REPO/'skills/usefulcharts-style/scripts'))
from assess_illustrated_review import assess

OBS={
 'instruments':dict(before=['Abstract category names had no visible object examples.','The repeated outline had no specific exploration prompts.','The image-free body required readers to supply their own mental pictures.'],repairs=['Fifteen inspected specimens are bound to visible category codes.','Neighboring-sheet fragments were removed with measured object viewports.','Mechanism captions answer the five panel prompts while preserving all 71 categories.'],composition='Five family panels retain a readable tree and a clearly owned specimen column.',image_usefulness='Bell, kazoo, violin, winds and signal tools are recognizable and linked to their mechanism codes.',image_integration='The safe crops contain complete objects; names, example codes and mechanism captions remain separate vector text.',playful_discovery='Strike or pluck, the kazoo question and signal prompts have answers in their own panels.',legibility='Whole poster and 1510-pixel detail retain readable branch labels and 14-pixel minimum captions.',question=('Why is a kazoo grouped with drums?',['242','211'],'Membranophones: a singing or struck stretched membrane')),
 'bsd':dict(before=['The long release lists lacked recognizable historical objects.','All families relied on the same text-only treatment.','The Berkeley tail offered little help tracing shared code across panels.'],repairs=['Six period-inspired scenes establish recognizable computing contexts without claiming exact historical machines.','The Berkeley pocket now shows the typed 4.4BSD Lite paths.','Trace-the-pipes and compare-the-cousins prompts are tied to existing records.'],composition='Balanced family panels now have warm material illustrations and a small code-sharing inset.',image_usefulness='Teletype, minicomputer, PC, disks, network and workstation archetypes distinguish computing contexts.',image_integration='Every scene is inside its family and explicitly marked illustrative period hardware.',playful_discovery='Pipes, hardware changes and one-source/three-paths prompts lead to printed release notes.',legibility='The PDF and dense Berkeley detail keep dates, release names and paired relationship references readable.',question=('Which systems receive code from 4.4BSD Lite?',['lite','f2','n1','os2'],'Berkeley inset and the three named destination records')),
 'mars':dict(before=['No spacecraft images distinguished the mission architectures.','Large released calendar pockets had no visual invitation.','Text-only campaign counts obscured the difference between campaigns and components.'],repairs=['Seven source-attributed spacecraft views cover four national programs.','Orbiters, cruise hardware and surface vehicles are compared in actual vacant pockets.','All date and component-span attributes remain identical; a draft count error and a context-panel collision were corrected.'],composition='Images and questions occupy the former reference pocket and released lower rows without growing the canvas.',image_usefulness='Four reference-guided NASA craft illustrations are joined by USSR museum, ISAS/JAXA Nozomi and DLR Mars 96 reference images.',image_integration='Field-guide frames explicitly state that picture positions are not calendar dates; exact records remain in the tracks.',playful_discovery='Vehicle counts, Viking component bars and Nozomi failure invite tracing information already printed.',legibility='The final dark PDF preserves date marks, line types and labels; text/image geometry has no conflicts.',question=('How can two Viking campaigns represent four vehicles?',['viking1','viking2'],'Separate orbiter and lander operation bars and the vehicle-count card')),
 'civilizations':dict(before=['All six historical branches were text-heavy and visually anonymous.','The reader had no recognizable species guide.','Long event sequences gave little help following a ship through different encounters.'],repairs=['Six generic representatives and four ship illustrations appear within their relevant branches.','Portraits are labelled as illustrations rather than dated historical people.','All 155 attributed records and original reading relationships remain intact.'],composition='Navy image pockets punctuate the six warm-paper histories while actor colors and coalition diagrams stay clear.',image_usefulness='Vulcan, Klingon, Cardassian, Borg, Ferengi and human representatives are visually distinct; ships anchor named stories.',image_integration='Images share a navy field and captions and have explicit record ownership without pretending to date the generic portraits.',playful_discovery='Follow-the-ship prompts and the two-Borg-stories comparison guide exploration across existing history.',legibility='The dense detail and independent PDF render preserve 18-pixel event bodies and 14-pixel credits.',question=('How do the two Borg stories in 2401 differ?',['st-116','st-118'],'The Borg branch and its separate Jurati/Jupiter-hive comparison')),
 'starships':dict(before=['The only ship illustrations were small trail-end silhouettes.','Large released early and future lanes lacked useful visual explanation.','The difference between a named line and one physical hull was mostly textual.'],repairs=['Seven large ship views fill independently checked released pockets.','Black image mats were blended into the space field without changing the original assets.','The twelve trail-end illustrations, 79 physical ships, all printed fragments and exact calendar marks remain.'],composition='The existing wake plot is complemented by recognizable silhouettes in lanes that have finished.',image_usefulness='NX, classic Enterprise, Defiant, Bird-of-Prey, Discovery, Voyager and Protostar have readable large profiles.',image_integration='Large views have named record ownership and explicit non-date positions; small images keep the original trail endpoints.',playful_discovery='Same-name/same-hull and known/unknown launch challenges have answers in the original records.',legibility='The ship-gallery detail is clean, and unchanged notes and date coordinates pass the independent record comparison.',question=('Does the same ship name always identify the same physical hull?',['defiant-first','defiant-second'],'Defiant records and typed relationship labels')),
}

def main():
    out=ROOT/'artifacts/reviews';checks={r['case']:r for r in json.loads((out/'independent-checks.json').read_text())};assessments=[]
    for case,obs in OBS.items():
        folder=ROOT/'artifacts/revision-2'/case;source=json.loads((folder/'source.json').read_text(encoding='utf-8'))
        records=source.get('nodes') or source.get('ships') or [n for k in ['events','origins','future','branches'] for n in source[k]]
        images=json.loads((folder/'art-map.json').read_text())
        # The small retained trail images are not used to satisfy the enlarged-image gate.
        images=[a for a in images if not a['placement_id'].startswith('trail-')]
        for a in images:
            path=Path(a['path']);path=path if path.is_absolute() else ROOT/path
            a['path']=str(path);a['recognized_at_placed_size']=True
        placement_map=json.loads((folder/'art-map.json').read_text())
        reviewed_ids={a['placement_id'] for a in images}
        for placement in placement_map:
            if placement['placement_id'] in reviewed_ids:placement['recognized_at_placed_size']=True
            else:placement['review_scope']='Retained small trail marker; not used to satisfy the large-image recognition gate.'
        (folder/'art-map.json').write_text(json.dumps(placement_map,indent=2)+'\n')
        artifacts={kind:dict(path=str(folder/file),sha256=hashlib.sha256((folder/file).read_bytes()).hexdigest()) for kind,file in [('whole','poster.png'),('detail','detail.png')]}
        question,anchors,location=obs['question']
        review=dict(schema_version=1,brief='Playful illustrated educational diagram; preserve the complete selected inventory.',artifacts=artifacts,reviewed_images=True,content_verified=checks[case]['source_preserved'],technical_verified=checks[case]['status']=='pass',required_groups=sorted({g for a in images for g in a['groups']}),record_ids=[n['id'] for n in records],minimum_body_regions=2,body_images=images,discovery_invitations=[dict(question=question,anchors=anchors,answer_location=location)],dimensions={name:dict(score=3,observation=obs[name]) for name in ['composition','image_usefulness','image_integration','playful_discovery','legibility']},before_weaknesses=obs['before'],repairs_observed=obs['repairs'],unresolved_defects=[],reference_density_status='pending')
        result=assess(review,out);assert result['declared_illustrated_brief_pass'],(case,result)
        (out/(case+'-illustrated-review.json')).write_text(json.dumps(review,indent=2)+'\n')
        (out/(case+'-assessment.json')).write_text(json.dumps(result,indent=2)+'\n');assessments.append(dict(case=case,**result))
    (out/'illustrated-assessments.json').write_text(json.dumps(assessments,indent=2)+'\n')
    paragraphs=['# Illustrated discovery review — 13 September 2026','The five diagrams were revised after the user rejected technically correct but visually dry work. The final SVG/PNG and an actual Poppler render of every one-page PDF were inspected at whole-poster and detailed reading scales. All 384 selected records remain. The illustrated reviews use a conservative 3/4 in every dimension, not an averaged score or a claim of exceptional quality.','The helper confirms evidence hashes and declared review completeness. It does not see pixels or certify these judgments. Independent record, date, image/text and PDF checks are recorded in independent-checks.json.','## Visible changes']
    for case,obs in OBS.items():
        check=checks[case];paragraphs += ['### '+case.replace('-',' ').title(),'Before: '+' '.join(obs['before']),'Observed repair: '+' '.join(obs['repairs']),f'Retained records: {check["records"]}. Total area change versus the immediately preceding diagram: {check["area_change_percent"]:+.2f}%.']
    paragraphs += ['## Evaluation evidence','Three isolated Luna high runs each opened all six raw candidate images and independently rejected the text-only and header-only candidates while accepting the body-integrated candidate. This is a narrow discrimination test on one museum classification case, not broad evidence that a model can produce excellent diagrams in every domain. The final instrument poster additionally adopts the suggested mechanism captions.','A default Spark command control passed the 12 review-boundary tests. A later final-runtime Spark control passed those tests and the 11 panel/viewport tests after a real nested-SVG measurement defect was corrected. Both used strict isolated runtime workspaces; model, exact output paths, tool errors, read surface and payload integrity were checked.','## Tradeoffs and remaining limits','BSD and instruments grow in area by 39.72% while retaining type size and all records. The Star Trek civilization chart grows by 10.24%. Mars and the spacecraft atlas retain their exact canvas sizes and calendar x coordinates. Image coverage improves, but record count per unit area decreases where the page grows; this is reported rather than described as a density improvement.','The selected information is preserved, not a census of every possible fact in these topics. No matched reference-density census or UsefulCharts aesthetic-parity assessment is complete. The skill remains validating. The source material and rights provenance are preserved; generated specimens and species representatives are illustrative, not engineering drawings or exact historical portraits.','The isolated reviewers occasionally called generated artwork a photograph and generally used generous scores. Asset provenance was checked independently, and their ratings were not treated as objective aesthetic measurements.']
    (out/'visual-review.md').write_text('\n\n'.join(paragraphs)+'\n',encoding='utf-8')
    print(json.dumps(dict(reviews=len(assessments),declared_gates_pass=all(r['declared_illustrated_brief_pass'] for r in assessments))))
if __name__=='__main__':main()
