#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Create focused, isolated output contracts for the palette revision."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
directory=ROOT/'evaluations/colorset-audit/prompts';directory.mkdir(parents=True,exist_ok=True)
common='''Use only the loaded skill and normal local tools. Treat its bundle as read-only and write all task files at the workspace root or the requested output paths. Read ../prompt.md first. Use the complete applicable reference or template and the bundled script; do not inspect helper implementation or acceptance examples. Report actual gate outcomes.\n\n'''
prompts={
'hierarchy-lens':'''Create a 120-record synthetic hierarchy as an offline analytical explorer at output/explorer.html, and a decision-growth view of the same source at output/decision.html. Keep output/source.json as the shared original input. Use the bundled demo and explicit demo composition policy. The active authored palette must be colorset2 because the simultaneous categorical lenses and numeric heat bands need multiple labeled categories; use the bundled exact palette and do not invent hues. Build outputs and record the exact commands in output/commands.md. This request is for files only; evaluator-side browser checks will inspect them.''',
'usefulcharts-style':'''Render the bundled starter lineage template without changing its invented records or relationships. Preserve output/source.json as the copied source. Create output/poster.svg, output/poster.html and output/render.json with the bundled renderer. Use the template's canonical colorset2 family colors, since four simultaneous craft families require independently labeled category cues. This is a render contract rather than a new historical research or visual-criticism task. Verify successful output and explain the active palette in output/palette.md.''',
'compose-synchronized-svg':'''Use the bundled compact composition brief template unchanged except for a colorset1 theme, title Palette Contract, and provenance describing synthetic acceptance values. Generate output/diagram.svg, output/plan.json and output/composition.json with the documented preflight, compiler and composer. Save the authored brief as output/brief.json. Run static validation and save output/static.json. This is a deterministic file-generation contract; evaluator-side browser checks will inspect its actual palette and states. Preserve the template's semantic state and renderer families.''',
'diagram-composition':'''Create a compact original SVG explaining one fictional documentation workflow with two panels: one taxonomy of Draft and Reviewed documents, and one two-column comparison matrix of those categories. Use native panels with direct labels and one exact colorset1 accent for each concept, plus neutral surfaces. Use the documented native pipeline, and save output/brief.json, output/plan.json, output/panels.json, output/diagram.svg and output/composition.json. This is a deterministic file-generation contract; evaluator-side browser checks will inspect the result. Avoid invented directional relations between the taxonomy and comparison.''',
'hyperframes-explainer':'''Validate the bundled starter brief and build it at output/project using the documented preflight/build workflow. Keep the copied editable input at output/brief.json. Write output/preflight.json and output/build.json. Preserve the starter's numerical semantics and exact colorset1 role paints. This request is a project-generation contract only; omit package installation and video encoding. Evaluator-side browser and existing media evidence cover the unchanged renderer.''',
'video':'''Create a planning-only scene contract by copying the complete bundled scene-contract.json template to output/scene-contract.json. Retain its two existing elements, shared events and signal connector. Use a colorset1 stage background and colorset1 connector paint. Validate the contract without requiring source asset files, because no producer files are supplied. Save output/validation.json and output/palette.md identifying preserved imported source media as distinct from authored stage and connectors. No renderer or MP4 is requested.''',
'manim-svg-video':'''Create a simple source SVG at output/source.svg with an opaque white background, one red rectangle and one dark label. All paints must be colorset1 exact tokens. Use the bundled Manim compositor in dry-run mode to prepare this one SVG as a 3-second replacement sequence with 640x360 dimensions and 5 fps. Keep the source unchanged and produce output/composition/composition-manifest.json and output/composition/manim_svg_video_scene.py. The Manim-authored wrapper must also use the default colorset1 token paints. This is a dry-run contract; no MP4 is requested.'''
}
for name,prompt in prompts.items():(directory/(name+'.md')).write_text(common+prompt+'\n',encoding='utf-8')
print('Created seven isolated palette output contracts.')
