/* Browser source. Mathematical data and D3 are embedded by build_decision_deck.ts. */
(() => {
'use strict';
const D=JSON.parse(document.getElementById('simulation-data').textContent);
const $=id=>document.getElementById(id);
const colors=['#9e1b32','#333e48','#828282'];
const usd=(v,d=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:d,minimumFractionDigits:d}).format(v);
const num=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
const pct=(v,d=1)=>(v*100).toFixed(d)+'%';
const compact=v=>d3.format('~s')(v).replace('G','B');
const bp=D.breakpoints;
const short=D.baselines.short, long=D.baselines.long;
const shortFreeze='Fixed: Luna tariff proxy; 5 tools × 2k tokens; 24,120 output tokens; full eligible-prefix reuse; one attempt.';
const longFreeze='Fixed: Luna tariff proxy; 39 tools × 20k tokens; 160k output tokens; 20k summaries; cold compactor and rebuilt cache.';
const priceNote='Published GitHub token rates, frozen on 06 Sep 2026. Token value before plan allowances, tax, capacity or subscription effects. These are hypothetical ledgers, not Pi or Copilot executions.';
const qualityNote='Quality assumptions: p0=80.90%, onset=100k, beta=0.2. The critical-fact link multiplies success odds by f^(10 × compactions). The average-fidelity rival uses mean per-call retention. Neither link is calibrated to these target models. Cost per completion includes spend on failures.';
const series=(key,label,outcome='attempt_usd',scale=1)=>({label,values:D.curves[key].map(r=>({x:r.x,y:r[outcome]*scale,...Object.fromEntries(Object.entries(r).filter(([k])=>k!=='x'))}))});
const flat=(label,min,max,y)=>({label,values:[{x:min,y},{x:max,y}]});
let N=1000000, index=0, value=0, playing=false, raf=0, activeConfig=null;
const scenes=[
{id:'parameters',topic:'THE PARAMETERS',title:'One variable at a time',essential:'The selected input moves. The rest of each scenario stays fixed.',caveat:'Model selection changes a bundle. Quality and failure costs need their own scenarios.',kind:'overview',plot:'Cost drivers considered in the model',notes:'The inventory separates varied, fixed and unresolved factors. “Fixed” means held constant, not negligible or validated. The core ledger contains 36 numeric or policy inputs. Candidate discovery can still miss relevant factors.'},
{id:'system',topic:'01 / SYSTEM PROMPT',title:'A stable prefix is paid repeatedly',essential:'One write, then five cached reads in the short session.',caveat:'The prompt stays identical across calls. A changed prefix or tariff boundary changes this result.',min:0,max:10000,step:250,initial:1000,label:'Additional system tokens',format:num,monthly:true,plot:'Monthly incremental token cost',xLabel:'Additional stable system tokens',yLabel:()=>`Additional USD / ${compact(N)} tasks`,frozen:shortFreeze,notes:priceNote+' User-prefix and schema size have the same direct arithmetic only when placement, persistence and cache eligibility match.',build:()=>[series('system:short','Additional cost','attempt_usd',N)].map(s=>({...s,values:s.values.map(r=>({...r,y:r.y-short.attempt_usd*N}))})),result:x=>[usd(.00000035*x*N,N===1000?2:0),`additional per month at ${num(N)} tasks`]},
{id:'tools',topic:'02 / TOOL CALLS',title:'One fewer call saves more than its payload',essential:'Removing a round trip also removes one replay of the growing context.',caveat:'Output and success stay frozen. The curve does not price evidence lost by removing a tool.',min:0,max:10,step:1,initial:4,label:'Tool calls per task',format:num,monthly:true,plot:'Task volume × exact request ledger',xLabel:'Tool calls per task',yLabel:()=>`USD / ${compact(N)} submitted tasks`,frozen:shortFreeze,notes:priceNote+' Each tool adds one model round trip. The total output budget is redistributed over the remaining calls. Tool execution fees are zero.',build:()=>[series('tools:short','Token cost','attempt_usd',N)],referenceX:5,referenceLabel:'Baseline: 5 tools',result:(x,ys)=>[usd(ys[0],N===1000?2:0),`${usd(short.attempt_usd*N-ys[0],N===1000?2:0)} saved versus 5 tools`]},
{id:'output',topic:'03 / OUTPUT TOKENS',title:'Output volume has a larger direct effect',essential:'A 20% output reduction saves about 17% of the short-task bill.',caveat:'The simulation holds success fixed. A shorter answer can be cheaper without being sufficient.',min:.5,max:1.5,step:.02,initial:.8,label:'Total output relative to baseline',format:x=>pct(x,0),monthly:true,plot:'Answer and reasoning tokens per completed attempt',xLabel:'Output budget / baseline',xFormat:x=>pct(x,0),yLabel:()=>`USD / ${compact(N)} submitted tasks`,frozen:shortFreeze,notes:priceNote+' The reasoning share stays fixed. Answer tokens persist into later calls; reasoning tokens do not. This creates both output and replay savings.',build:()=>[series('output:short','Token cost','attempt_usd',N)],referenceX:1,referenceLabel:'24,120 tokens',result:(x,ys)=>[usd(short.attempt_usd*N-ys[0],N===1000?2:0),`saved at ${num(24120.0674*x)} output tokens per task`]},
{id:'cache',topic:'04 / CACHE REUSE',title:'Cache misses amplify long-session costs',essential:'The same hit rate has a different dollar impact under each context policy.',caveat:'No strategy crossing appears in the 0–100% range under this ledger. Cache TTL and prefix identity remain unresolved.',min:0,max:1,step:.01,initial:.9,label:'Eligible-prefix cache hit fraction',format:pct,monthly:true,plot:'No cap versus a fixed 180k compaction cap',xLabel:'Cache hit fraction',xFormat:x=>pct(x,0),yLabel:()=>`USD / ${compact(N)} submitted tasks`,frozen:longFreeze+' Quality frozen.',notes:priceNote+' A miss writes new cacheable input at $0.25/M tokens, rather than using the ordinary $0.20 input bucket. Disabling caching is a different policy.',build:()=>[series('cache-compact:long','180k cap','attempt_usd',N),series('cache-free:long','No cap','attempt_usd',N)],result:(x,ys)=>[usd(ys[1]-ys[0],0),'less with the 180k cap at this hit fraction']},
{id:'cap',topic:'05 / COMPACTION TRIGGER',title:'The cheapest cap sits below the price tier',essential:'The minimum grid plateau is 156k–160k in this long workload.',caveat:'This is a cost-only minimum in the searched 50k–400k range. Summary quality stays lossless.',min:50000,max:400000,step:1000,initial:180000,label:'Compaction trigger',format:x=>compact(x)+' tokens',monthly:true,plot:'Compaction cost, cache rebuild and replay cost together',xLabel:'Compaction trigger / tokens',xFormat:compact,yLabel:()=>`USD / ${compact(N)} submitted tasks`,frozen:longFreeze+' Cache hits 100%; quality loss zero.',notes:priceNote+' The check runs before each main call. A tool payload can cross the trigger first. The summarizer reads that entire context and may pay the long tier itself. The 1k grid and 500-token challenge grid find the same minimum cost. Values between sampled caps are step displays, not smoothed estimates.',build:()=>[{...series('cap:long','Compaction policy','attempt_usd',N),step:true},flat('No cap',50000,400000,long.attempt_usd*N)],referenceX:200000,referenceLabel:'Price tier >200k',band:[156000,160000],result:(x,ys)=>[usd(ys[0],0),`${pct(1-ys[0]/(long.attempt_usd*N))} below no cap; minimum ${usd(bp.cap_minimum.usd*N,0)}`]},
{id:'trajectory',topic:'06 / SIMULATED SESSION',title:`Compaction pays back at call ${D.trajectory_payback.first_payback_call}`,essential:`The first summary adds cost at call ${D.trajectory_payback.first_compaction_call}. Later replay savings recover it.`,caveat:'This is one simulated 40-call session. The x axis is model calls, not real dates or measured history.',kind:'trajectory',min:1,max:40,step:1,initial:40,label:'Main call in the simulated session',format:num,plot:'Active context and cumulative spend on a shared call axis',frozen:longFreeze+' All output and quality assumptions frozen.',notes:priceNote+' Cumulative spend includes any compaction immediately before the corresponding main call. Dots mark compactions. Both policies do the same modeled work.',result:x=>{const a=D.trajectory.compact.find(r=>r.x===x),b=D.trajectory.free.find(r=>r.x===x),diff=b.cost-a.cost;return[usd(Math.abs(diff),3),`${diff<0?'extra cost':'saved'} through call ${x}; cap policy ${usd(a.cost,3)}`]}},
{id:'fidelity',topic:'07 / SUMMARY FIDELITY',title:'Small information losses can erase the saving',essential:'The critical-fact model switches preference near 96.45% retention per summary.',caveat:'The average-fidelity rival finds no crossing from 90% to 100%. The assumed loss mechanism changes the decision.',min:.9,max:1,step:.001,initial:.99,label:'Per-summary fact retention',format:x=>pct(x,1),plot:'Provider spend per expected completed task',xLabel:'Per-summary fact retention',xFormat:x=>pct(x,0),yLabel:()=> 'USD / completed task · log scale',logY:true,frozen:'Fixed: long workload, cap 180k, onset 100k, beta 0.2, 10 critical facts, one attempt.',notes:qualityNote,build:()=>[series('fidelity-critical:long','180k / critical facts','correct_usd'),flat('No cap',.9,1,D.curves['quality-free:long'][0].correct_usd),series('fidelity-average:long','180k / average fidelity','correct_usd')],referenceX:bp.fidelity.critical,referenceLabel:'Break-even: 96.45%',result:(x,ys)=>[ys[0]<ys[1]?'180k cap':'No cap',`${usd(ys[0])} versus ${usd(ys[1])} per completion under critical-fact loss`]},
{id:'rot',topic:'08 / CONTEXT DEGRADATION',title:'The price of context depends on quality loss',essential:'A longer exposure raises cost per success even when the token bill stays unchanged.',caveat:'Beta is an assumed log-odds penalty. These curves do not establish when a real model starts failing.',min:0,max:1,step:.01,initial:.2,label:'Degradation slope beta',format:x=>x.toFixed(2),plot:'Long-context quality sensitivity',xLabel:'Assumed beta / 100k excess token-calls',yLabel:()=> 'USD / completed task',frozen:'Fixed: onset 100k, fidelity 99%, 10 critical facts, long ledger and prices.',notes:qualityNote+' Exposure averages max(context − onset, 0)/100k over main calls. The 180k strategy remains cheaper across this beta range under the displayed assumptions. Different onset, task mix and fact timing remain sensitivity gaps.',build:()=>[series('rot-compact:long','180k cap','correct_usd'),series('rot-free:long','No cap','correct_usd')],result:(x,ys)=>[usd(ys[1]),`no-cap cost per completion; 180k cap ${usd(ys[0])}`]},
{id:'models',topic:'09 / MODEL SELECTION',title:'The quality floor determines the eligible model',essential:'Among the six retained AA profiles, choose the cheapest point that clears the floor.',caveat:'AA benchmark averages are proxies. Small score differences lack paired uncertainty in the retrieved data.',kind:'models',min:.75,max:.95,step:.001,initial:.85,label:'Required single-attempt success',format:pct,plot:'Published AA Terminal-Bench v2.1 aggregates',frozen:'Evidence: 89 tasks, 3 repeats per task, Terminus 2 harness. Six matched profiles, not the full leaderboard.',notes:'Source: Artificial Analysis Terminal-Bench v2.1. Output tokens include answer plus reasoning for the entire task. Published average cost and pass@1 refer to the benchmark workload. Mean token counts do not identify standard deviation. The Intelligence Index is neither the same workload nor a success probability. Changing models changes price, tokens and quality together.'},
{id:'loss',topic:'10 / COST OF FAILURE',title:'Higher success pays off when failure is expensive',essential:'Luna max and Sol xhigh exchange preference at about $3.82 per failed task.',caveat:'Only provider spend and the declared failure loss enter this comparison. Other models may be preferable outside this pair.',min:0,max:10,step:.05,initial:3.8,label:'Loss per failed task',format:usd,plot:'Expected cost = provider spend + failure probability × loss',xLabel:'USD lost per failed task',xFormat:x=>usd(x,0),yLabel:()=> 'Expected USD / submitted task',frozen:'Fixed: each model’s published AA average cost and pass@1; one attempt; no human or latency cost.',notes:priceNote+' This is an analytic decision scenario using AA point estimates, not a causal comparison of target harnesses. Conditional mean tokens and task difficulty can alter the threshold.',build:()=>Object.entries(D.loss).map(([label,values])=>({label,values})),referenceX:bp.loss,referenceLabel:'Break-even: $3.82',result:(x,ys)=>[ys[0]<=ys[1]?'Luna max':'Sol xhigh',`${usd(Math.min(...ys))} expected cost per task at ${usd(x)} failure loss`]},
{id:'retries',topic:'11 / RETRY DEPENDENCE',title:'Persistent failures weaken retry gains',essential:'Three attempts meet 95% completion only while persistence rho stays below about 23.38%.',caveat:'Retries cost the same and stop at success. The persistent-failure mixture is an assumption, not a measured rate.',min:0,max:1,step:.01,initial:.2,label:'Persistent-failure mixture rho',format:pct,plot:'Completion probability with a bounded attempt cap',xLabel:'Persistence rho',xFormat:x=>pct(x,0),yLabel:()=> 'Completion probability',yFormat:x=>pct(x,0),yDomain:[.78,1],frozen:'Fixed: p0=80.90%, short-task cost, K=1 / 2 / 3, perfect success detection.',notes:'With probability rho, all planned attempts share one Bernoulli outcome; otherwise they are independent. Exact enumeration verifies completion and paid-attempt formulas. At rho=1, failed tasks pay all retries with no completion gain. Independence does not lower the cohort cost per completion when each attempt has identical cost and success.',build:()=>[3,2,1].map(k=>({label:`${k} attempt${k>1?'s':''}`,values:D.retry[String(k)]})),referenceX:bp.retry,referenceLabel:'95% limit: rho 23.38%',referenceY:.95,result:(x,ys)=>[pct(ys[0]),`${ys[0]>=.95?'meets':'misses'} the 95% floor with three attempts`]},
{id:'routing',topic:'12 / MODEL ESCALATION',title:'Fallback depends on conditional recovery',essential:'Sol must recover at least 73.82% of Luna’s failures to reach 95% combined success.',caveat:'Sol’s overall AA pass rate cannot stand in for success on the harder subset that Luna failed.',min:0,max:1,step:.01,initial:.75,label:'Fallback success given first-model failure',format:pct,plot:'Luna first, then Sol xhigh on a detected failure',xLabel:'Conditional recovery probability',xFormat:x=>pct(x,0),yLabel:()=> 'Combined completion probability',yFormat:x=>pct(x,0),yDomain:[.78,1],frozen:'Fixed: Luna AA pass@1, both AA mean costs, perfect validator, one fallback, no extra overhead.',notes:'Expected spend = C_Luna + (1 − p_Luna) C_Sol. Combined success = p_Luna + (1 − p_Luna) r. The conditional Sol cost is assumed equal to its published marginal mean. False acceptances, false rejections and costly difficult fallback tasks can reverse this result.',build:()=>[{label:'Luna then Sol',values:D.routing}],referenceX:bp.routing,referenceLabel:'95% limit: r 73.82%',referenceY:.95,result:(x,ys)=>[pct(ys[0]),`${usd(D.routing[0].spend*1000,2)} per 1,000 submitted tasks; fallback cost frozen`]},
{id:'variability',topic:'13 / MONTHLY UNCERTAINTY',title:'Volume averages out noise, not shared shocks',essential:'Independent task variability shrinks with volume. A shared monthly shock leaves a risk floor.',caveat:'These are assumed CVs and exact standard deviations. They are not empirical AA uncertainty or a confidence interval.',min:3,max:6,step:.025,initial:6,label:'Monthly tasks',format:x=>num(10**x),plot:'Relative standard deviation of the monthly bill',xLabel:'Submitted tasks per month · log scale',xFormat:compact,xLog:true,yLabel:()=> 'Monthly cost SD / mean',yFormat:x=>pct(x,1),frozen:'Fixed: output CV=100%, fixed input bill; shared output-multiplier CV=0% or 30%.',notes:'For independent unit-mean positive task and month multipliers, relative output variance is 1/N + shockCV² + shockCV²/N. Multiply its square root by the output share of the bill. The 30% common multiplier is hypothetical. Token-success dependence and invoice allowances remain outside the calculation.',build:()=>[{label:'30% common shock',values:D.spread['0.3']},{label:'Independent tasks only',values:D.spread['0']}],result:(x,ys)=>[pct(ys[0]),`relative monthly SD with a common shock; independent only ${pct(ys[1],2)}`]},
{id:'decisions',topic:'THE DECISION BOUNDARIES',title:'Each recommendation has a condition',essential:'The useful result is the point where a choice changes, together with what could move that point.',caveat:'No finite variable review guarantees completeness. Task quality, validator errors and real billing can still reverse these choices.',kind:'summary',plot:'Conditional rules from the displayed curves',notes:'Arithmetic and browser checks verify implementation. They do not validate the modeled system. See the source snapshot, variable inventory and method for unresolved structural assumptions.'}
];
function nearest(rows,x,step=false){if(x<=rows[0].x)return rows[0].y;if(x>=rows.at(-1).x)return rows.at(-1).y;const j=d3.bisector(d=>d.x).right(rows,x);const a=rows[j-1],b=rows[j];return step?a.y:a.y+(b.y-a.y)*(x-a.x)/(b.x-a.x)}
function moneyTick(y){return Math.abs(y)>=1000?'$'+compact(y):'$'+d3.format('~g')(y)}
function plot(container,seriesList,opts={}){
  const width=Math.max(260,container.clientWidth),height=opts.height||(width<500?310:440);
  const m={top:34,right:18,bottom:61,left:width<450?59:74};
  const points=seriesList.flatMap(s=>s.values), xe=d3.extent(points,p=>p.x);
  const x=(opts.xLog?d3.scaleLog():d3.scaleLinear()).domain(opts.xDomain||xe).range([m.left,width-m.right]);
  const allY=points.map(p=>p.y).concat(opts.referenceY===undefined?[]:[opts.referenceY]);
  const ye=d3.extent(allY);let yd=opts.yDomain;
  if(!yd) yd=opts.logY?[Math.max(1e-8,ye[0]*.85),ye[1]*1.2]:[opts.zero===false?Math.max(0,ye[0]-(ye[1]-ye[0])*.12):0,ye[1]===0?1:ye[1]*1.14];
  const y=(opts.logY?d3.scaleLog():d3.scaleLinear()).domain(yd).range([height-m.bottom,m.top]);
  const svg=d3.select(container).append('svg').attr('id',opts.id||'decision-chart').attr('viewBox',`0 0 ${width} ${height}`).attr('role','img').attr('font-family','Segoe UI, Arial, sans-serif').attr('data-colorset','colorset1').attr('data-pattern-id','d3-code-assist-decision-curves');
  svg.append('title').text(opts.title||scenes[index].plot);svg.append('desc').text(opts.desc||scenes[index].essential+' '+scenes[index].caveat);
  const clipId=(opts.id||'decision-chart')+'-clip';
  svg.append('defs').append('clipPath').attr('id',clipId).append('rect').attr('x',m.left).attr('y',m.top).attr('width',width-m.right-m.left).attr('height',height-m.top-m.bottom);
  const logTicks=(domain,powersOnly=false)=>{const values=[];for(let k=Math.floor(Math.log10(domain[0]));k<=Math.ceil(Math.log10(domain[1]));k++)for(const f of (powersOnly?[1]:[1,2,5])){const v=f*10**k;if(v>=domain[0]&&v<=domain[1])values.push(v);}return values;};
  const xTicks=opts.xLog?logTicks(x.domain(),Math.log10(x.domain()[1]/x.domain()[0])>=2):null;
  const yTicks=opts.logY?logTicks(y.domain()):null;
  const gridAxis=d3.axisLeft(y).ticks(5).tickSize(-(width-m.left-m.right)).tickFormat('');
  if(yTicks)gridAxis.tickValues(yTicks);
  svg.append('g').attr('class','grid').attr('transform',`translate(${m.left},0)`).call(gridAxis);
  if(opts.band)svg.append('rect').attr('x',x(opts.band[0])).attr('y',m.top).attr('width',Math.max(4,x(opts.band[1])-x(opts.band[0]))).attr('height',height-m.top-m.bottom).attr('fill','#ffccd5').attr('opacity',.7);
  const xf=opts.xFormat||((v)=>Math.abs(v)>0&&Math.abs(v)<1?d3.format('.1f')(v):compact(v)),yf=opts.yFormat||moneyTick;
  const xAxis=d3.axisBottom(x).ticks(width<500?4:6).tickFormat(xf).tickSizeOuter(0);
  const yAxis=d3.axisLeft(y).ticks(5).tickFormat(yf).tickSizeOuter(0);
  if(xTicks)xAxis.tickValues(xTicks);
  if(yTicks)yAxis.tickValues(yTicks);
  svg.append('g').attr('class','x-axis').attr('transform',`translate(0,${height-m.bottom})`).call(xAxis);
  svg.append('g').attr('class','y-axis').attr('transform',`translate(${m.left},0)`).call(yAxis);
  svg.append('text').attr('class','axis-title').attr('data-axis','x').attr('x',(m.left+width-m.right)/2).attr('y',height-14).attr('text-anchor','middle').text(opts.xLabel||'');
  svg.append('text').attr('class','axis-title').attr('data-axis','y').attr('x',m.left).attr('y',15).text(opts.yLabel||'');
  if(opts.referenceY!==undefined)svg.append('line').attr('class','reference').attr('x1',m.left).attr('x2',width-m.right).attr('y1',y(opts.referenceY)).attr('y2',y(opts.referenceY));
  if(opts.referenceX!==undefined&&opts.referenceX!==null){
    svg.append('line').attr('class','reference').attr('x1',x(opts.referenceX)).attr('x2',x(opts.referenceX)).attr('y1',m.top).attr('y2',height-m.bottom);
    svg.append('text').attr('class','annotation').attr('text-anchor','middle').attr('x',Math.min(width-110,Math.max(m.left+105,x(opts.referenceX)))).attr('y',m.top+18).text(opts.referenceLabel||'Decision boundary');
  }
  const marks=svg.append('g').attr('clip-path',`url(#${clipId})`);
  seriesList.forEach((s,i)=>{
    const line=d3.line().x(d=>x(d.x)).y(d=>y(d.y)).curve(s.step?d3.curveStepAfter:d3.curveLinear);
    marks.append('path').datum(s.values).attr('class','series').attr('data-series',s.label).attr('stroke',colors[i%3]).attr('stroke-dasharray',i===1?'8 5':i===2?'2 5':null).attr('d',line);
    if(opts.events)marks.selectAll(`circle.event-${i}`).data(s.values.filter(d=>d.compact)).join('circle').attr('class',`event-${i}`).attr('cx',d=>x(d.x)).attr('cy',d=>y(d.y)).attr('r',4).attr('fill',colors[i%3]);
  });
  const guide=svg.append('g').attr('class','cursor-group');
  const guideLine=guide.append('line').attr('class','guide').attr('y1',m.top).attr('y2',height-m.bottom);
  const dots=guide.selectAll('circle').data(seriesList).join('circle').attr('class','selected').attr('r',5).attr('stroke',(_,i)=>colors[i%3]);
  function update(v){guideLine.attr('x1',x(v)).attr('x2',x(v));dots.attr('cx',x(v)).attr('cy',s=>y(nearest(s.values,v,s.step)));}
  const tooltip=d3.select(container).append('div').attr('class','tooltip').attr('role','tooltip');
  svg.append('rect').attr('data-chart-hit','true').attr('x',m.left).attr('y',m.top).attr('width',width-m.left-m.right).attr('height',height-m.top-m.bottom).attr('fill','#ffffff').attr('opacity',0)
    .on('pointermove',event=>{const px=d3.pointer(event,svg.node())[0];const v=x.invert(Math.max(m.left,Math.min(width-m.right,px)));update(v);tooltip.style('display','block').style('left',Math.min(width-240,Math.max(0,px-100))+'px').style('top',(m.top+40)+'px').html(`<b>${xf(v)}</b>`+seriesList.map(s=>`<br>${s.label}: ${yf(nearest(s.values,v,s.step))}`).join(''));})
    .on('pointerleave',()=>{tooltip.style('display','none');update(opts.cursor());})
    .on('click',event=>{const v=x.invert(d3.pointer(event,svg.node())[0]);setValue(scenes[index].xLog?Math.log10(v):v);});
  return {svg:svg.node(),update,x,y,width,height,marks};
}
function setResult(main,detail){$('result').innerHTML=`<strong>${main}</strong><span>${detail}</span>`;}
function setLegend(items){$('legend').innerHTML=items.map((s,i)=>`<span class="legend-item" data-index="${i}"><i class="swatch" style="border-color:${colors[i%3]}"></i>${s.label}</span>`).join('');}
function topics(summary=false){
  const entries=summary?[
    ['01','Stable prompt','+$350 / million tasks per extra 1k tokens','system'],['02','Compaction cap','156k–160k minimizes this cost-only grid','cap'],
    ['03','Summary quality','Critical-fact break-even ≈96.45% retention','fidelity'],['04','Failure value','Luna / Sol crossing ≈$3.82 per failure','loss'],
    ['05','Retries','95% completion requires rho ≤23.38%','retries'],['06','Escalation','95% completion requires recovery ≥73.82%','routing']
  ]:[
    ['01','Prompts & context','System, user prefix, schemas, order, retained history','system'],['02','Tools & output','Call count, batching, payload size, answer and reasoning','tools'],
    ['03','Caching & tariffs','Read, write, misses, prefix stability, TTL, price tiers','cache'],['04','Compaction & quality','Trigger, summary size, cache rebuild, information loss, context rot','cap'],
    ['05','Models & recovery','Mean tokens, success, retries, fallback, validator errors','models'],['06','Scale & economics','Monthly volume, variance, common shocks, failure cost, allowances','variability']
  ];
  $('chart').innerHTML=`<div class="parameter-list">${entries.map(e=>`<button class="parameter-topic" type="button" data-jump="${e[3]}"><b><span class="index">${e[0]}</span>${e[1]}</b><small>${e[2]}</small></button>`).join('')}<p class="full-note">${summary?'All thresholds are conditional on the stated workload and mechanism.':'Short case: 5 tools. Long case: 39 tools. Prices and AA aggregates stay separate from assumed quality and variability.'}</p></div>`;
  $('chart').querySelectorAll('[data-jump]').forEach(el=>el.onclick=()=>go(el.dataset.jump));
}
function renderModels(){
  const label=['Luna max','Terra max','Sol max','Sol xhigh','Astra medium','Astra high'];
  const ps=D.profiles.map((p,i)=>({x:p.cost_usd,y:p.pass1,label:label[i],id:i+1,tokens:p.output_tokens}));
  const cfg=plot($('chart'),[{label:'AA profiles',values:[{x:.035,y:.78},{x:.8,y:.93}]}],{id:'models-chart',xLog:true,xDomain:[.035,.85],yDomain:[.77,.96],xFormat:moneyTick,yFormat:x=>pct(x,0),xLabel:'Published USD / task · log scale',yLabel:'Published pass@1',cursor:()=>.035});
  d3.select(cfg.svg).selectAll('.series,.cursor-group,[data-chart-hit]').remove();
  const g=d3.select(cfg.svg).append('g');
  const frontier=[];for(const p of [...ps].sort((a,b)=>a.x-b.x)){if(!frontier.length||p.y>frontier.at(-1).y)frontier.push(p);}
  g.append('path').datum(frontier).attr('class','series').attr('stroke','#828282').attr('stroke-dasharray','3 5').attr('d',d3.line().x(p=>cfg.x(p.x)).y(p=>cfg.y(p.y)));
  const pts=g.selectAll('circle.model').data(ps).join('circle').attr('class','model').attr('cx',p=>cfg.x(p.x)).attr('cy',p=>cfg.y(p.y)).attr('r',7).attr('fill','#ffffff').attr('stroke','#333e48').attr('stroke-width',2);
  const offsets=[[-4,25],[12,43],[-22,25],[-25,-35],[0,-61],[12,-14]];
  g.selectAll('text.model-label').data(ps).join('text').attr('class','model-label').attr('x',(p,i)=>Math.min(cfg.width-25,cfg.x(p.x)+offsets[i][0])).attr('y',(p,i)=>cfg.y(p.y)+offsets[i][1]).attr('text-anchor','middle').text(p=>p.id);
  const line=g.append('line').attr('class','guide').attr('x1',cfg.x(.035)).attr('x2',cfg.x(.85));
  $('legend').innerHTML=ps.map(p=>`<span>${p.id} ${p.label}</span>`).join('');
  return v=>{line.attr('y1',cfg.y(v)).attr('y2',cfg.y(v));const choice=ps.filter(p=>p.y>=v).sort((a,b)=>a.x-b.x)[0];pts.attr('fill',p=>choice&&p.id===choice.id?'#9e1b32':'#ffffff').attr('stroke',p=>p.y>=v?'#9e1b32':'#828282').attr('opacity',p=>p.y>=v?1:.55);setResult(choice?choice.label:'No qualifying model',choice?`${usd(choice.x)} / task; ${pct(choice.y)} pass@1; ${num(choice.tokens)} output tokens / task`:`None of these six AA point estimates reaches ${pct(v)}.`);};
}
function build(){
  const s=scenes[index];$('eyebrow').textContent=s.topic;$('heading').textContent=s.title;$('essential').textContent=s.essential;$('caveat').textContent=s.caveat;$('plot-title').textContent=s.plot;$('frozen').textContent=s.frozen||'';
  $('chart').innerHTML='';$('legend').innerHTML='';$('result').innerHTML='';$('counter').textContent=`${String(index+1).padStart(2,'0')} / ${scenes.length}`;$('progress').style.width=((index+1)/scenes.length*100)+'%';
  $('previous').disabled=index===0;$('next').disabled=index===scenes.length-1;$('volume').disabled=!s.monthly;$('control-row').hidden=s.min===undefined;$('replay').disabled=s.min===undefined;$('export').disabled=!!s.kind&&['overview','summary'].includes(s.kind);
  if(s.kind==='overview'||s.kind==='summary'){topics(s.kind==='summary');activeConfig=null;return;}
  $('parameter').min=s.min;$('parameter').max=s.max;$('parameter').step=s.step;$('parameter-label').textContent=s.label;
  if(s.kind==='models'){activeConfig={update:renderModels()};setValue(value,false);return;}
  if(s.kind==='trajectory'){
    const top=document.createElement('div'),bottom=document.createElement('div');$('chart').append(top,bottom);
    const a=['compact','free'].map((id,i)=>({label:i?'No cap':'180k cap',values:D.trajectory[id].filter(r=>r.x>0).map(r=>({...r,y:r.context}))}));
    const b=['compact','free'].map((id,i)=>({label:i?'No cap':'180k cap',values:D.trajectory[id].filter(r=>r.x>0).map(r=>({...r,y:r.cost}))}));
    setLegend(a);
    const height=$('chart').clientWidth<500?255:Math.max(195,Math.min(255,Math.floor((innerHeight-415)/2)));
    const p1=plot(top,a,{id:'context-history',height,xLabel:'Main call',yLabel:'Active main-call input / tokens',yFormat:compact,referenceY:200000,events:true,cursor:()=>value});
    const p2=plot(bottom,b,{id:'cost-history',height,xLabel:'Main call',yLabel:'Cumulative USD / session',events:true,referenceX:D.trajectory_payback.first_payback_call,referenceLabel:`Cumulative payback: call ${D.trajectory_payback.first_payback_call}`,cursor:()=>value});
    activeConfig={update:v=>{p1.update(v);p2.update(v);setResult(...s.result(v));}};
  }else{
    const data=s.build();setLegend(data);
    const cfg=plot($('chart'),data,{...s,yLabel:s.yLabel(),cursor:()=>s.xLog?10**value:value});
    activeConfig={update:v=>{const x=s.xLog?10**v:v;cfg.update(x);setResult(...s.result(v,data.map(q=>nearest(q.values,x,q.step))));}};
  }
  setValue(value,false);
}
function setValue(v,stop=true){const s=scenes[index];if(s.min===undefined)return;if(stop)pause();value=Math.max(s.min,Math.min(s.max,Math.round((v-s.min)/s.step)*s.step+s.min));$('parameter').value=value;$('parameter-value').textContent=s.format(value);activeConfig?.update(value);}
function go(id){pause();index=typeof id==='number'?Math.max(0,Math.min(scenes.length-1,id)):Math.max(0,scenes.findIndex(s=>s.id===id));value=scenes[index].initial||0;history.replaceState(null,'','#'+scenes[index].id);build();}
function pause(){playing=false;cancelAnimationFrame(raf);$('replay').textContent='Play sweep';}
function replay(){if(playing){pause();return;}const s=scenes[index];if(s.min===undefined)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){setValue(s.max);return;}playing=true;$('replay').textContent='Pause';const start=performance.now();function frame(t){if(!playing)return;const u=Math.min(1,(t-start)/9000);setValue(s.min+(s.max-s.min)*u,false);if(u<1)raf=requestAnimationFrame(frame);else pause();}raf=requestAnimationFrame(frame);}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function notes(){pause();const s=scenes[index];$('detail-body').innerHTML=`<h3>${s.title}</h3><p>${s.notes||''}</p><p class="badge-note">Simulation only. No target programs, agents, inference APIs or tool executions.</p><h3>What the numbers mean</h3><p>Exact deterministic cells have no Monte Carlo error. Quality parameters, benchmark transfer and uncertainty models remain assumptions. A range across assumptions is not a confidence interval. Monthly token values do not identify your actual invoice.</p><h3>Evidence snapshot</h3><ul>${D.sources.map(a=>`<li><a href="${a.url}" target="_blank" rel="noreferrer">${a.title}</a></li>`).join('')}</ul><h3>Model-specific output tokens</h3><p>Published averages for an entire Terminal-Bench task. No empirical standard deviation appears in the retrieved aggregate.</p><table><thead><tr><th>Configuration</th><th>Output tokens</th><th>Pass@1</th><th>USD/task</th></tr></thead><tbody>${D.profiles.map(p=>`<tr><td>${p.model}</td><td>${num(p.output_tokens)}</td><td>${pct(p.pass1)}</td><td>${usd(p.cost_usd,3)}</td></tr>`).join('')}</tbody></table><h3>Variable inventory</h3><p>These treatments describe the core curve study. Analytic extensions also vary failure value, retry dependence, fallback recovery, volume and assumed dispersion. Prefix TTL, capacity, task-selection bias, invoice allowances, validator errors and token-success dependence remain unresolved.</p><table><thead><tr><th>Candidate</th><th>Core treatment</th><th>Unit</th></tr></thead><tbody>${D.inventory.map(v=>`<tr><td>${v.label}</td><td>${v.treatment}</td><td>${v.unit}</td></tr>`).join('')}</tbody></table><h3>Reproducibility</h3><p>2,124 deterministic core cells. The 1k cap grid and 500-token challenge grid agree on the minimum cost. The candidate minimum is conditional on 50k–400k caps and this fixed workload. History charts show a simulated session, not real historical observations.</p><div class="note-actions"><button id="download-curves" type="button">Download plotted data</button></div>`;$('detail').showModal();$('download-curves').onclick=()=>download(JSON.stringify(D,null,2),'code-assist-decision-data.json','application/json');}
$('parameter').oninput=e=>setValue(+e.target.value);$('previous').onclick=()=>go(index-1);$('next').onclick=()=>go(index+1);$('replay').onclick=replay;$('volume').onchange=e=>{N=+e.target.value;pause();build();};$('notes').onclick=notes;$('close-notes').onclick=()=>$('detail').close();$('home').onclick=e=>{e.preventDefault();go(0)};
$('export').onclick=()=>{const svgs=[...$('chart').querySelectorAll('svg')];svgs.forEach((svg,i)=>{const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font-family:Arial,sans-serif;fill:#333e48;font-size:13px}.grid line{stroke:#e7e7e7}.grid path{display:none}.domain,.tick line{stroke:#cfcfcf}.series{fill:none;stroke-width:3}.reference{stroke:#828282;stroke-width:1.5;stroke-dasharray:4 5}.guide{stroke:#9e1b32;stroke-width:1.5;stroke-dasharray:3 4}.selected{stroke-width:2.5;fill:#ffffff}.annotation{font-weight:600;paint-order:stroke;stroke:#f7f7f7;stroke-width:5px;stroke-linejoin:round}';clone.prepend(style);download(new XMLSerializer().serializeToString(clone),`decision-${scenes[index].id}-${i+1}.svg`,'image/svg+xml');});};
$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
document.addEventListener('keydown',e=>{if($('detail').open||['INPUT','SELECT','BUTTON','A'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(index+1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(index-1);}if(e.code==='Space'){e.preventDefault();replay();}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{pause();build()},120)});
window.addEventListener('hashchange',()=>go(location.hash.slice(1)));
window.DECK={go,set:setValue,scenes:scenes.map(s=>({id:s.id,title:s.title,min:s.min,max:s.max,initial:s.initial})),get state(){return {scene:scenes[index].id,index,value,N,playing,result:$('result').textContent}},data:D};
go(location.hash.slice(1)||'parameters');
})();
