---
# mermaid: config begin
config:
  theme: "base"
  themeVariables:
    background: "#ffffff"
    primaryColor: "#ffccd5"
    primaryTextColor: "#333e48"
    primaryBorderColor: "#9e1b32"
    secondaryColor: "#cdf3ff"
    secondaryTextColor: "#333e48"
    secondaryBorderColor: "#007298"
    tertiaryColor: "#e7e7e7"
    tertiaryTextColor: "#333e48"
    tertiaryBorderColor: "#9c9c9c"
    lineColor: "#696969"
    textColor: "#333e48"
    mainBkg: "#cdf3ff"
    nodeBkg: "#cdf3ff"
    nodeBorder: "#9e1b32"
    clusterBkg: "#e7e7e7"
    clusterBorder: "#9c9c9c"
    defaultLinkColor: "#696969"
    edgeLabelBackground: "#ffffff"
    labelColor: "#333e48"
    titleColor: "#333e48"
    emUiFill: "#ffffff"
    emUiStroke: "#9c9c9c"
    emProcessorFill: "#f9ccff"
    emProcessorStroke: "#652f6c"
    emReadModelFill: "#dbffcc"
    emReadModelStroke: "#45842a"
    emCommandFill: "#cdf3ff"
    emCommandStroke: "#007298"
    emEventFill: "#ffe5cc"
    emEventStroke: "#e77204"
    emArrowhead: "#9e1b32"
    emRelationStroke: "#696969"
# mermaid: config end
# mermaid: metadata begin
mermaid:
  colorset: "colorset2"
  mode: "extended"
  palette: "full-color-style"
# mermaid: metadata end
---
eventmodeling
  tf 01 ui UserInterface
  tf 02 pcr Processor
  tf 03 rmo ReadModel
  tf 04 cmd Command
  tf 05 evt Event
