---
# mermaid: config begin
config:
  theme: "base"
  themeVariables:
    THEME_COLOR_LIMIT: 12
    background: "#ffffff"
    primaryColor: "#9e1b32"
    primaryTextColor: "#ffffff"
    primaryBorderColor: "#9e1b32"
    secondaryColor: "#007298"
    secondaryTextColor: "#ffffff"
    secondaryBorderColor: "#007298"
    tertiaryColor: "#e77204"
    tertiaryTextColor: "#000000"
    tertiaryBorderColor: "#e77204"
    lineColor: "#696969"
    textColor: "#333e48"
    mainBkg: "#9e1b32"
    nodeBkg: "#9e1b32"
    nodeBorder: "#9e1b32"
    clusterBkg: "#e7e7e7"
    clusterBorder: "#9c9c9c"
    defaultLinkColor: "#696969"
    edgeLabelBackground: "#ffffff"
    labelColor: "#ffffff"
    titleColor: "#333e48"
    git0: "#9e1b32"
    gitBranchLabel0: "#ffffff"
    cScale0: "#9e1b32"
    cScale1: "#007298"
    cScale2: "#e77204"
    cScale3: "#45842a"
    cScale4: "#652f6c"
    cScale5: "#f1c319"
    cScale6: "#6d1222"
    cScale7: "#004d66"
    cScale8: "#994a00"
    cScale9: "#294d19"
    cScale10: "#431f47"
    cScale11: "#98700c"
    cScaleLabel0: "#ffffff"
    cScaleLabel1: "#ffffff"
    cScaleLabel2: "#000000"
    cScaleLabel3: "#000000"
    cScaleLabel4: "#ffffff"
    cScaleLabel5: "#000000"
    cScaleLabel6: "#ffffff"
    cScaleLabel7: "#ffffff"
    cScaleLabel8: "#ffffff"
    cScaleLabel9: "#ffffff"
    cScaleLabel10: "#ffffff"
    cScaleLabel11: "#000000"
    cScaleInv0: "#ffffff"
    cScaleInv1: "#ffffff"
    cScaleInv2: "#000000"
    cScaleInv3: "#000000"
    cScaleInv4: "#ffffff"
    cScaleInv5: "#000000"
    cScaleInv6: "#ffffff"
    cScaleInv7: "#ffffff"
    cScaleInv8: "#ffffff"
    cScaleInv9: "#ffffff"
    cScaleInv10: "#ffffff"
    cScaleInv11: "#000000"
  themeCSS: ".node > rect, .node > circle, .node > ellipse, .node > polygon, .node > path, rect.actor, .note, .task, .task0, .task1, .task2, .task3 { stroke-width: 0 !important; }"
  mindmap:
    padding: 6
# mermaid: config end
# mermaid: metadata begin
mermaid:
  colorset: "colorset2"
  mode: "extended"
  palette: "full-color-style"
# mermaid: metadata end
---
mindmap
  root((Mind root))
    Mind branch 01
    Mind branch 02
    Mind branch 03
    Mind branch 04
    Mind branch 05
    Mind branch 06
    Mind branch 07
    Mind branch 08
    Mind branch 09
    Mind branch 10
    Mind branch 11
