---
# mermaid: config begin
config:
  theme: "base"
  themeVariables:
    background: "#ffffff"
    primaryColor: "#ffccd5"
    primaryTextColor: "#333e48"
    primaryBorderColor: "#9e1b32"
    secondaryColor: "#cdf3ff"
    secondaryTextColor: "#333e48"
    secondaryBorderColor: "#007298"
    tertiaryColor: "#e7e7e7"
    tertiaryTextColor: "#333e48"
    tertiaryBorderColor: "#9c9c9c"
    lineColor: "#696969"
    textColor: "#333e48"
    mainBkg: "#cdf3ff"
    nodeBkg: "#cdf3ff"
    nodeBorder: "#9e1b32"
    clusterBkg: "#e7e7e7"
    clusterBorder: "#9c9c9c"
    defaultLinkColor: "#696969"
    edgeLabelBackground: "#ffffff"
    labelColor: "#333e48"
    titleColor: "#333e48"
    pie1: "#9e1b32"
    pie2: "#007298"
    pie3: "#e77204"
    pie4: "#45842a"
    pie5: "#652f6c"
    pie6: "#828282"
    pie7: "#4f4f4f"
    pie8: "#e8002a"
    pie9: "#ffccd5"
    pie10: "#cdf3ff"
    pie11: "#ffe5cc"
    pie12: "#dbffcc"
    pieTitleTextColor: "#333e48"
    pieLegendTextColor: "#333e48"
    pieSectionTextColor: "#ffffff"
    pieStrokeColor: "#ffffff"
# mermaid: config end
# mermaid: metadata begin
mermaid:
  colorset: "colorset2"
  mode: "extended"
  palette: "full-color-style"
# mermaid: metadata end
---
pie title Base mix
  "Primary" : 40
  "Accent" : 30
  "Muted" : 30
