---
# mermaid: config begin
config:
  theme: "base"
  themeVariables:
    background: "#ffffff"
    primaryColor: "#ffccd5"
    primaryTextColor: "#333e48"
    primaryBorderColor: "#9e1b32"
    secondaryColor: "#cdf3ff"
    secondaryTextColor: "#333e48"
    secondaryBorderColor: "#007298"
    tertiaryColor: "#e7e7e7"
    tertiaryTextColor: "#333e48"
    tertiaryBorderColor: "#9c9c9c"
    lineColor: "#696969"
    textColor: "#333e48"
    mainBkg: "#cdf3ff"
    nodeBkg: "#cdf3ff"
    nodeBorder: "#9e1b32"
    clusterBkg: "#e7e7e7"
    clusterBorder: "#9c9c9c"
    defaultLinkColor: "#696969"
    edgeLabelBackground: "#ffffff"
    labelColor: "#333e48"
    titleColor: "#333e48"
    radar:
      axisColor: "#333e48"
      axisLabelColor: "#333e48"
      graticuleColor: "#828282"
      legendBoxBorderColor: "#9c9c9c"
      legendBoxBackgroundColor: "#ffffff"
# mermaid: config end
# mermaid: metadata begin
mermaid:
  colorset: "colorset2"
  mode: "extended"
  palette: "full-color-style"
# mermaid: metadata end
---
radar-beta
  title Base radar
  axis coverage["Coverage"], classdefs["ClassDefs"], checks["Checks"]
  curve target["Target"]{5, 5, 5}
  curve current["Current"]{4, 5, 5}
  max 5
  min 0
