#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-skill-polish-smoke",
  "--title",
  "Metro Square Composition Smoke",
  "--topic",
  "alignment and square borders",
  "--output-id",
  "metro-square-smoke",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "July 4, 2026",
  "--audience",
  "general technical viewers",
  "--duration",
  "4.0",
  "--fps",
  "6",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "Square borders are required.",
  "--fact",
  "Panels should align to a visible grid.",
  "--anchor",
  "straight panel borders",
  "--anchor",
  "shared baselines",
  "--system-label",
  "source",
  "--system-label",
  "event",
  "--system-label",
  "signal",
  "--system-label",
  "bus",
  "--system-label",
  "bounded queue",
  "--system-label",
  "worker pool",
  "--system-label",
  "DB",
  "--system-label",
  "retry policy",
  "--system-label",
  "dead-letter",
  "--system-label",
  "throughput",
  "--system-label",
  "throttle"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
