#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-a-harness-plugin",
  "--title",
  "What is a Harness Plugin",
  "--topic",
  "What is a Harness Plugin",
  "--output-id",
  "what-is-a-harness-plugin",
  "--pattern",
  "layered-architecture",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A harness plugin is a distribution mechanism for reusable harness customization.",
  "--fact",
  "The exact packaging differs by product, but the common pattern is to bundle runtime capabilities for install, sharing, versioning, and governance.",
  "--fact",
  "GitHub Copilot CLI plugins can bundle agents, skills, hooks, and MCP configuration.",
  "--fact",
  "Claude Code plugins can bundle skills, agents, hooks, and MCP servers from marketplaces.",
  "--fact",
  "OpenCode plugins are JavaScript or TypeScript modules loaded locally or from npm to add hooks, tools, and integrations.",
  "--fact",
  "Plugins package multiple runtime behaviors into one installable unit.",
  "--fact",
  "Distribution is governance: plugins standardize the approved way to work across a team.",
  "--fact",
  "Plugins can lower cost with efficient defaults or raise cost by injecting noisy context and expensive tool calls everywhere.",
  "--anchor",
  "plugin bundle cube",
  "--anchor",
  "detachable module blocks",
  "--anchor",
  "GitHub plugin manifest card",
  "--anchor",
  "Claude marketplace allowlist gate",
  "--anchor",
  "OpenCode npm module",
  "--anchor",
  "versioning and upgrade arrows",
  "--anchor",
  "good plugin versus noisy plugin split",
  "--anchor",
  "team-wide install lane",
  "--layer-label",
  "Plugin bundle",
  "--layer-label",
  "Skills",
  "--layer-label",
  "Tools",
  "--layer-label",
  "Apps/connectors",
  "--layer-label",
  "Hooks",
  "--layer-label",
  "MCP config",
  "--layer-label",
  "Agent profile",
  "--concern-label",
  "Policy",
  "--concern-label",
  "Marketplace",
  "--concern-label",
  "Install/update",
  "--concern-label",
  "Versioning",
  "--concern-label",
  "Governance",
  "--concern-label",
  "Context cost"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
