#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Create the manually verified events and sports candidate pools."""

from __future__ import annotations

import json
from pathlib import Path


CHECKED = "2026-07-11"
DISCOVER = "https://discoveratlanta.com/events/family/"
CUMMING = "https://www.cityofcumming.net/events/month/2026-07"


def candidate(
    category_id: str,
    name: str,
    venue: str,
    address: str,
    city: str,
    zip_code: str,
    official_url: str,
    *,
    corroborating_url: str = "",
    start_date: str = "",
    end_date: str = "",
    start_time: str = "",
    subtype: str,
    price_level: str = "unknown",
    family: int = 4,
    unique: int = 4,
    evidence: int = 4,
    value: int = 3,
    hours: float = 2.0,
    cost_note: str = "Check current pricing and availability before leaving.",
    why_good: str,
    caveat: str = "Schedule and capacity can change; recheck the linked source.",
    age_notes: str = "Broad family appeal; confirm any event-specific age policy.",
    indoor_outdoor: str = "mixed",
    urgency: int = 5,
) -> dict:
    return {
        "category_id": category_id,
        "name": name,
        "venue": venue,
        "address": address,
        "city": city,
        "state": "GA",
        "zip": zip_code,
        "latitude": None,
        "longitude": None,
        "official_url": official_url,
        "corroborating_url": corroborating_url or official_url,
        "checked_date": CHECKED,
        "start_date": start_date,
        "end_date": end_date or start_date,
        "start_time": start_time,
        "rating": None,
        "review_count": None,
        "price_level": price_level,
        "subtype": subtype,
        "family_fit_1_5": family,
        "uniqueness_1_5": unique,
        "evidence_quality_1_5": evidence,
        "value_1_5": value,
        "time_urgency_1_5": urgency,
        "estimated_visit_hours": hours,
        "cost_note": cost_note,
        "why_good": why_good,
        "caveat": caveat,
        "age_notes": age_notes,
        "indoor_outdoor": indoor_outdoor,
        "image_candidates": [
            {
                "page_url": official_url,
                "method": "Capture the official page hero or Open Graph image.",
                "rights_note": "Official promotional source; attribute the page and limit use to this private family-planning guide.",
            }
        ],
    }


events = [
    candidate("events-festivals-live-shows", "Ultimate Garth: Garth Brooks Tribute", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/ultimate-garth-garth-brooks-tribute-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-11", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, hours=2, why_good="A close-to-home outdoor concert that avoids an Atlanta drive.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Slide Into Sundays", "Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/slide-into-sundays-at-city-center-2", corroborating_url=CUMMING, start_date="2026-07-12", end_date="2026-07-19", start_time="12:00", subtype="recurring kids water-play day", price_level="free", family=5, unique=3, value=5, hours=3, why_good="Bounce houses and water activities make this one of the easiest local family days.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Hooray for Jump Day", "Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/hooray-for-jump-day-at-city-center-4", corroborating_url=CUMMING, start_date="2026-07-15", end_date="2026-07-29", start_time="13:00", subtype="recurring bounce-house day", price_level="free", family=5, unique=3, value=5, hours=3, why_good="A flexible local weekday activity with a long open window.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "AudioVault in Concert", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/audiovault-in-concert-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-17", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, hours=2, why_good="A free Friday-night rock and alternative show minutes from home.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Dock Rock Radio", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/dock-rock-radio-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-18", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, hours=2, why_good="A free Saturday yacht-rock concert with an easy drive home.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Brotherhood: A Doobie Brothers Tribute", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/brotherhood-a-doobie-brothers-tribute-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-24", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, urgency=4, hours=2, why_good="A later-July no-ticket local concert option.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Double Take in Concert", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/double-take-in-concert-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-25", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, urgency=4, hours=2, why_good="A relaxed free community concert for a later weekend.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Kidz Dayz: Back-to-School Bash", "Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/kidz-dayz-at-city-center", corroborating_url=CUMMING, start_date="2026-07-30", start_time="11:00", subtype="kids community event", price_level="free", family=5, unique=3, value=5, urgency=4, hours=3, why_good="A child-focused local event with activities and a community donation drive.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "84: Van Halen Tribute", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/84-van-halen-tribute-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-07-31", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, urgency=3, hours=2, why_good="A high-energy free tribute concert close to home.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Jackson Chase in Concert", "Lou Sobh Amphitheater at Cumming City Center", "423 Canton Rd", "Cumming", "30040", "https://www.cityofcumming.net/event/jackson-chase-in-concert-at-lou-sobh-amphitheater", corroborating_url=CUMMING, start_date="2026-08-01", start_time="20:00", subtype="free concert", price_level="free", family=4, unique=3, value=5, urgency=3, hours=2, why_good="An easy future Saturday concert in Cumming.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "T. rex: The Ultimate Predator", "Fernbank Museum of Natural History", "767 Clifton Rd NE", "Atlanta", "30307", "https://discoveratlanta.com/event/detail/t-rex-the-ultimate-predator/", corroborating_url="https://www.fernbankmuseum.org/experiences/exhibits/t-rex-the-ultimate-predator/", start_date="2026-07-11", end_date="2026-09-07", start_time="10:00", subtype="museum special exhibition", price_level="paid", family=5, unique=5, evidence=5, value=4, hours=3, why_good="Life-size models, fossils, interactives and a responsive T. rex make a strong mixed-age science day.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "All the Soccer Things at The Works", "The Works", "1295 Chattahoochee Ave NW", "Atlanta", "30318", "https://discoveratlanta.com/event/detail/all-the-soccer-things-at-the-works/", corroborating_url="https://theworksatl.com/", start_date="2026-07-11", end_date="2026-07-19", start_time="12:00", subtype="soccer watch-party series", price_level="free-entry", family=5, unique=5, evidence=5, value=5, hours=4, why_good="Combines live match viewing, music, global food and shopping during the World Cup finish.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Sloomoo Football Club", "Sloomoo Institute Atlanta", "3637 Peachtree Rd NE", "Atlanta", "30319", "https://discoveratlanta.com/event/detail/sloomoo-football-club/", corroborating_url="https://sloomooinstitute.com/pages/atlanta", start_date="2026-07-11", end_date="2026-07-19", subtype="immersive slime and soccer activation", price_level="paid", family=5, unique=5, evidence=4, value=3, hours=2, why_good="A rare crossover of soccer energy and hands-on slime play.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Critter Fun Day", "Noah's Ark Animal Sanctuary", "712 L G Griffin Rd", "Locust Grove", "30248", "https://discoveratlanta.com/event/detail/critter-fun-day-at-noah-s-ark-animal-sanctuary-2/", corroborating_url="https://noahs-ark.org/", start_date="2026-07-11", subtype="junior animal program", price_level="registration", family=5, unique=5, evidence=4, value=4, hours=3, why_good="A hands-on animal-focused morning designed for younger visitors.", caveat="This is a long metro drive and may require advance registration.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Minions & Monsters Summer Fun Day", "Xfinity at The Battery Atlanta", "800 Battery Ave SE", "Atlanta", "30339", "https://discoveratlanta.com/event/detail/minions-monsters-summer-fun-day/", start_date="2026-07-11", subtype="character-themed family day", price_level="free-entry", family=5, unique=4, evidence=4, value=5, hours=2, why_good="A playful character event that can pair with The Battery and Truist Park.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "PeachTrees on Peachtree Family Fun Mini Market", "Underground Atlanta", "50 Upper Alabama St", "Atlanta", "30303", "https://discoveratlanta.com/event/detail/peachtrees-on-peachtree-family-fun-mini-market/", start_date="2026-07-11", subtype="family mini market", price_level="free", family=5, unique=4, evidence=4, value=5, hours=2, why_good="A free downtown market with family activities and local vendors.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Summer Goals Tour at Target", "Target Buckhead South", "2539 Piedmont Rd NE", "Atlanta", "30324", "https://discoveratlanta.com/event/detail/summer-goals-tour-at-target/", start_date="2026-07-11", subtype="soccer-themed retail activation", price_level="free", family=4, unique=4, evidence=4, value=5, hours=1.5, why_good="A short free soccer-themed activation that is easy to combine with another Buckhead stop.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Summer Break Magic Show", "Lawrenceville Arts Center", "125 N Clayton St", "Lawrenceville", "30046", "https://discoveratlanta.com/event/detail/summer-break-magic-show/", corroborating_url="https://www.auroratheatre.com/", start_date="2026-07-15", subtype="family magic show", price_level="paid", family=5, unique=4, evidence=4, value=4, hours=1.5, why_good="A compact indoor performance suited to a hot or rainy vacation day.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Family Day at Top Dawg Tavern", "Top Dawg Tavern Bethlehem", "656 Exchange Cir", "Bethlehem", "30620", "https://discoveratlanta.com/event/detail/family-day-at-top-dawg-tavern/", start_date="2026-07-18", subtype="restaurant family day", price_level="free-entry", family=5, unique=3, evidence=4, value=4, hours=2, why_good="Food and scheduled family activities make this a low-planning outing.", caveat="The drive is longer than most restaurant outings.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Final Match World Soccer Block Party", "Yeppa & Co Buckhead", "306 Buckhead Ave NE", "Atlanta", "30305", "https://discoveratlanta.com/event/detail/final-match-world-soccer-block-party-at-yeppa-co/", start_date="2026-07-19", subtype="World Cup final block party", price_level="free-entry", family=4, unique=5, evidence=4, value=4, hours=4, why_good="Oversized screens and a live DJ create a high-energy final-match atmosphere.", caveat="Confirm the family policy and expected crowd conditions before attending.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "The LEGO Brand x FIFA Fan Fest", "Centennial Olympic Park", "265 Park Ave W NW", "Atlanta", "30313", "https://discoveratlanta.com/event/detail/the-lego-brand-x-fifa-fan-fest/", corroborating_url="https://atlantafwc26.com/fan-fest/", start_date="2026-07-11", end_date="2026-07-15", subtype="LEGO and soccer activation", price_level="free-registration", family=5, unique=5, evidence=5, value=5, hours=3, why_good="A highly unusual free combination of hands-on bricks and World Cup fan programming.", caveat="Every guest age 2 and older needs a Fan Festival registration ticket.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "American Tall Tales", "Center for Puppetry Arts", "1404 Spring St NW", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/american-tall-tales/", corroborating_url="https://puppet.org/", start_date="2026-07-11", end_date="2026-08-02", subtype="family puppet performance", price_level="paid", family=5, unique=5, evidence=4, value=4, hours=2.5, why_good="Live puppetry plus the museum creates a distinctive indoor cultural day.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Dinoverse VR & Fossil Exhibit", "Exhibition Hub Atlanta Art Center", "5660 Buford Hwy NE", "Doraville", "30340", "https://discoveratlanta.com/event/detail/dinoverse-vr-fossil-exhibit/", start_date="2026-07-11", end_date="2026-08-28", subtype="immersive dinosaur VR", price_level="paid", family=5, unique=5, evidence=4, value=3, hours=2, why_good="Virtual reality and fossils deliver a technology-heavy dinosaur experience.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Bubble Planet: Immersive Experience", "Exhibition Hub Atlanta Art Center", "5660 Buford Hwy NE", "Doraville", "30340", "https://discoveratlanta.com/event/detail/bubble-planet-immersive-experience/", start_date="2026-07-11", end_date="2026-08-28", subtype="immersive multisensory exhibit", price_level="paid", family=5, unique=5, evidence=4, value=3, hours=2, why_good="Large-scale bubbles and multisensory rooms are visually memorable for children.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Glow Nights", "Adventure Air Sports Kennesaw", "425 Ernest W Barrett Pkwy NW", "Kennesaw", "30144", "https://discoveratlanta.com/event/detail/glow-nights-at-adventure-air-sports/", corroborating_url="https://adventureairsports.com/", start_date="2026-07-11", end_date="2026-08-01", start_time="20:00", subtype="recurring glow trampoline night", price_level="paid", family=4, unique=4, evidence=4, value=3, hours=2, why_good="A neon after-dark active-play option for older children and teens.", age_notes="Best for children comfortable with trampoline and aerial activity rules.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Spookhouse Annie", "Center for Puppetry Arts", "1404 Spring St NW", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/spookhouse-annie/", corroborating_url="https://puppet.org/", start_date="2026-07-11", end_date="2026-11-01", subtype="family puppet performance", price_level="paid", family=4, unique=5, evidence=4, value=4, hours=2, why_good="An unusual spooky puppetry option with museum access nearby.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Uptown Market Atlanta", "The Lawn at Uptown", "2400 Garson Dr NE", "Atlanta", "30324", "https://discoveratlanta.com/event/detail/uptown-market-atlanta/", start_date="2026-07-11", end_date="2026-11-14", subtype="weekly food and craft market", price_level="free-entry", family=4, unique=3, evidence=4, value=5, hours=2.5, why_good="Food, crafts, live music and kid-friendly space support a flexible weekend stop.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Kid's Art Market", "Dunwoody/Chamblee rotating location", "4800 Ashford Dunwoody Rd", "Dunwoody", "30338", "https://discoveratlanta.com/event/detail/kids-art-market/", start_date="2026-07-11", end_date="2026-07-28", subtype="children's art market", price_level="free-entry", family=5, unique=5, evidence=3, value=5, hours=1.5, why_good="Children create and sell art in a peer-focused market setting.", caveat="The listing says the exact rotating location may be announced later; verify before travel.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Coffee & Chrome", "Jess Lucas Park", "680 S Central Ave", "Hapeville", "30354", "https://discoveratlanta.com/event/detail/coffee-chrome/", start_date="2026-07-11", end_date="2026-09-12", subtype="car and motorcycle show", price_level="free", family=4, unique=4, evidence=4, value=5, hours=2, why_good="A free classic-car morning that works well for mechanically curious children.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Around-the-World Popsicle Flavors", "Ponce City Market", "675 Ponce De Leon Ave NE", "Atlanta", "30308", "https://discoveratlanta.com/event/detail/around-the-world-inspired-popsicle-flavors-at-king-of-pops/", start_date="2026-07-11", end_date="2026-07-15", subtype="limited-time food experience", price_level="paid", family=5, unique=4, evidence=4, value=4, hours=1, why_good="A low-commitment tasting stop linked to the international soccer atmosphere.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Puppet Camp", "Center for Puppetry Arts", "1404 Spring St NW", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/puppet-camp/", corroborating_url="https://puppet.org/", start_date="2026-07-11", end_date="2026-07-31", subtype="creative day camp", price_level="registration", family=4, unique=5, evidence=4, value=3, hours=6, why_good="A focused hands-on performing-arts experience for children who enjoy making and storytelling.", caveat="Camp enrollment and age bands may be limited; verify availability.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Butterfly Encounter", "Chattahoochee Nature Center", "9135 Willeo Rd", "Roswell", "30075", "https://discoveratlanta.com/event/detail/butterfly-encounter/", corroborating_url="https://www.chattnaturecenter.org/", start_date="2026-07-11", end_date="2026-08-30", subtype="seasonal live-butterfly experience", price_level="paid", family=5, unique=5, evidence=4, value=4, hours=3, why_good="Walk among live butterflies and combine the encounter with trails and wildlife exhibits.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Family Day at Adventure Air Sports", "Adventure Air Sports Kennesaw", "425 Ernest W Barrett Pkwy NW", "Kennesaw", "30144", "https://discoveratlanta.com/event/detail/family-day-at-adventure-air-sports/", corroborating_url="https://adventureairsports.com/", start_date="2026-07-16", end_date="2027-05-06", start_time="12:00", subtype="recurring discounted active-play session", price_level="paid", family=5, unique=3, evidence=4, value=4, hours=3, why_good="A daytime active indoor option with a recurring family schedule.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "FIFA Fan Festival Atlanta", "Centennial Olympic Park", "265 Park Ave W NW", "Atlanta", "30313", "https://atlantafwc26.com/fan-fest/", corroborating_url="https://discoveratlanta.com/events/fifa-world-cup/", start_date="2026-07-11", end_date="2026-07-19", subtype="official World Cup fan festival", price_level="free-registration", family=5, unique=5, evidence=5, value=5, hours=5, why_good="Official large-screen matches, music, games, food and cultural programming create a once-in-a-generation Atlanta event.", caveat="Registration is required for every guest age 2 and older; clear-bag and cashless rules apply.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "FIFA World Cup 26 Atlanta Semifinal", "Mercedes-Benz Stadium", "1 AMB Dr NW", "Atlanta", "30313", "https://www.mercedesbenzstadium.com/events/fifa-world-cup-26-tm---semi-final", corroborating_url="https://atlantafwc26.com/atlantas-final-match-schedule-for-the-fifa-world-cup-2026-now-available/", start_date="2026-07-15", start_time="15:00", subtype="international soccer semifinal", price_level="premium-ticket", family=5, unique=5, evidence=5, value=2, hours=6, cost_note="Very high-demand event; use only official ticket channels and compare total costs.", why_good="The Atlanta semifinal is the most historically significant live sporting event in the vacation window.", caveat="Tickets and downtown logistics are difficult and expensive; gates open at noon.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Celebration of Soccer & Sound", "Piedmont Park", "1320 Monroe Dr NE", "Atlanta", "30306", "https://www.axios.com/local/atlanta/2026/07/10/ludacris-world-cup-fifa-festival-piedmont-park", corroborating_url="https://discoveratlanta.com/events/", start_date="2026-07-19", start_time="11:00", subtype="free soccer and music festival", price_level="free", family=5, unique=5, evidence=4, value=5, hours=6, why_good="A free World Cup closing-day festival with live music in Piedmont Park.", caveat="Expect a very large crowd and heat; verify the official event rules and transit plan.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Atlanta Dream vs. Portland Fire", "Gateway Center Arena", "2330 Convention Center Concourse", "College Park", "30337", "https://dream.wnba.com/news/next-stop-dream-season-2026-atlanta-dream-announces-regular-season-schedule", start_date="2026-07-11", subtype="WNBA game", price_level="paid", family=5, unique=5, evidence=5, value=4, hours=3, why_good="A live women's professional basketball game featuring the new Portland team.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Atlanta Dream vs. Seattle Storm", "Gateway Center Arena", "2330 Convention Center Concourse", "College Park", "30337", "https://dream.wnba.com/schedule/", corroborating_url="https://dream.wnba.com/news/next-stop-dream-season-2026-atlanta-dream-announces-regular-season-schedule", start_date="2026-07-12", start_time="20:00", subtype="WNBA game", price_level="paid", family=5, unique=4, evidence=4, value=4, hours=3, why_good="A second live WNBA option during the vacation weekend.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Gwinnett Stripers Disney Toy Story Night", "Gwinnett Field", "2500 Buford Dr", "Lawrenceville", "30043", "https://www.mlb.com/milb/gwinnett/news/homestand-highlights-stripers-start-their-engines-for-racing-night", start_date="2026-07-11", subtype="Triple-A baseball theme night", price_level="paid", family=5, unique=5, evidence=5, value=5, hours=4, why_good="Affordable close-up baseball plus a Toy Story theme and giveaway.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Gwinnett Stripers Sunday Funday", "Gwinnett Field", "2500 Buford Dr", "Lawrenceville", "30043", "https://www.mlb.com/milb/gwinnett/news/homestand-highlights-stripers-start-their-engines-for-racing-night", start_date="2026-07-12", subtype="Triple-A baseball family promotion", price_level="paid", family=5, unique=4, evidence=5, value=5, hours=4, why_good="Pre-game catch on the field and post-game kids run the bases add family participation.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Atlanta United 2 vs. Inter Miami CF II", "Turner Soccer Complex", "3200 George Busbee Pkwy NW", "Kennesaw", "30144", "https://www.atlutd.com/2/news/atlanta-united-2-announces-2026-mls-next-pro-regular-season-schedule", start_date="2026-07-11", subtype="MLS NEXT Pro soccer", price_level="paid", family=5, unique=4, evidence=5, value=5, hours=3, why_good="A lower-cost, more intimate soccer match during World Cup month.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Savanna Nights", "Zoo Atlanta", "800 Cherokee Ave SE", "Atlanta", "30315", "https://discoveratlanta.com/events/", corroborating_url="https://zooatlanta.org/", start_date="2026-07-11", end_date="2026-07-25", subtype="after-hours zoo event", price_level="paid", family=4, unique=5, evidence=3, value=3, hours=3, why_good="An evening zoo visit avoids some midday heat and adds special programming.", caveat="Verify age policy and the exact July occurrence before purchasing.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Fetes de Bayonne Celebration", "Cooks & Soldiers", "691 14th St NW", "Atlanta", "30318", "https://discoveratlanta.com/events/", corroborating_url="https://www.cooksandsoldiers.com/", start_date="2026-07-12", subtype="Basque cultural food celebration", price_level="paid", family=3, unique=5, evidence=3, value=3, hours=2, why_good="A distinctive taste of Basque festival culture without leaving Atlanta.", caveat="Confirm child-friendly hours and whether reservations or tickets are required.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Big Screen Classic Film Fest", "Aurora Cineplex", "5100 Commerce Pkwy", "Roswell", "30076", "https://discoveratlanta.com/events/", corroborating_url="https://www.auroracineplex.com/", start_date="2026-07-11", end_date="2026-08-05", subtype="classic film series", price_level="paid", family=4, unique=4, evidence=3, value=4, hours=3, why_good="A flexible indoor movie outing near home with repertory programming.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "300 and Troy: Odyssey Film Fest", "Aurora Cineplex", "5100 Commerce Pkwy", "Roswell", "30076", "https://discoveratlanta.com/events/", corroborating_url="https://www.auroracineplex.com/", start_date="2026-07-11", end_date="2026-07-16", subtype="themed film festival", price_level="paid", family=3, unique=4, evidence=3, value=4, hours=3, why_good="A short-run cinema series for older children interested in epic stories.", age_notes="Film ratings may be better suited to teens; review each title first.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Park It at the Hall", "College Football Hall of Fame", "250 Marietta St NW", "Atlanta", "30313", "https://discoveratlanta.com/events/", corroborating_url="https://www.cfbhall.com/", start_date="2026-07-11", end_date="2026-07-31", subtype="limited admission promotion", price_level="promotion", family=5, unique=4, evidence=3, value=5, hours=3, why_good="Interactive football challenges plus a potential vehicle-owner admission promotion.", caveat="Confirm the exact promotion eligibility before travel.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Beat The Bomb Summer Mission: America250", "Beat The Bomb Atlanta", "1483 Chattahoochee Ave NW", "Atlanta", "30318", "https://discoveratlanta.com/events/", corroborating_url="https://beatthebomb.com/atlanta", start_date="2026-07-11", end_date="2026-07-31", subtype="immersive team game", price_level="paid", family=4, unique=5, evidence=3, value=3, hours=2, why_good="A fast, cooperative technology game for families with older children.", age_notes="Check the minimum age, height and paint/foam/slime mission rules.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Atlanta Ice Cream Festival", "Piedmont Park", "1320 Monroe Dr NE", "Atlanta", "30306", "https://discoveratlanta.com/event/detail/atlanta-ice-cream-festival/", start_date="2026-07-25", subtype="food festival", price_level="free-entry", family=5, unique=5, evidence=4, value=5, urgency=4, hours=4, why_good="Free entry, live entertainment, kids activities and ice cream contests make a strong later-July family plan.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Music for the Very Young: The Lion and the Mouse", "Woodruff Arts Center", "1280 Peachtree St NE", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/music-for-the-very-young-the-lion-and-the-mouse/", start_date="2026-07-25", end_date="2026-08-02", subtype="early-childhood classical performance", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=4, hours=1.5, why_good="Classical music and storytelling are intentionally designed for young children.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Family Fun July Storytime: Planting a Rainbow", "College Park Library", "3647 Main St", "College Park", "30337", "https://discoveratlanta.com/event/detail/family-fun-july-storytime-planting-a-rainbow/", start_date="2026-07-29", subtype="storytime and craft", price_level="free", family=5, unique=3, evidence=4, value=5, urgency=4, hours=1.5, why_good="A free literacy-and-craft activity for younger children.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Sonic EXPO Atlanta 2026", "Cobb Galleria Centre", "2 Galleria Pkwy SE", "Atlanta", "30339", "https://discoveratlanta.com/event/detail/sonic-expo-atlanta-2026/", start_date="2026-08-07", end_date="2026-08-09", subtype="gaming fan convention", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=3, hours=6, why_good="A strong future geek-family event centered on Sonic games, creators and fans.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Piedmont Park Arts Festival", "Piedmont Park", "1320 Monroe Dr NE", "Atlanta", "30306", "https://discoveratlanta.com/event/detail/piedmont-park-arts-festival-returns-this-august/", start_date="2026-08-15", end_date="2026-08-16", subtype="outdoor arts festival", price_level="free-entry", family=5, unique=4, evidence=4, value=5, urgency=3, hours=4, why_good="A broad outdoor arts festival with family programming in a central park.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Chocolate Milk & Cookies", "Atlanta metropolitan venue", "1280 Peachtree St NE", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/chocolate-milk-cookies/", start_date="2026-08-22", subtype="family community event", price_level="unknown", family=4, unique=4, evidence=3, value=3, urgency=3, hours=3, why_good="A family-centered community experience with a distinctive theme.", caveat="The listing location is incomplete; verify venue and ticket details before planning.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "Yellow Daisy Festival", "Stone Mountain Park", "1000 Robert E Lee Blvd", "Stone Mountain", "30083", "https://discoveratlanta.com/event/detail/yellow-daisy-festival/", corroborating_url="https://www.stonemountainpark.com/", start_date="2026-09-10", end_date="2026-09-13", subtype="arts and crafts festival", price_level="parking-or-entry", family=5, unique=5, evidence=4, value=4, urgency=2, hours=6, why_good="One of Georgia's signature arts-and-crafts events in a full-day destination.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Stone Mountain Pumpkin Festival", "Stone Mountain Park", "1000 Robert E Lee Blvd", "Stone Mountain", "30083", "https://discoveratlanta.com/event/detail/stone-mountain-parks-pumpkin-festival/", corroborating_url="https://www.stonemountainpark.com/", start_date="2026-09-19", end_date="2026-11-01", subtype="fall family festival", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=2, hours=6, why_good="Daytime attractions and nighttime glow programming create a substantial future fall outing.", indoor_outdoor="mixed"),
    candidate("events-festivals-live-shows", "The Wizard of Oz", "Center for Puppetry Arts", "1404 Spring St NW", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/the-wizard-of-oz/", corroborating_url="https://puppet.org/", start_date="2026-09-16", end_date="2026-09-27", subtype="family puppet performance", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=2, hours=2.5, why_good="A familiar story interpreted through Atlanta's specialized puppetry institution.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Native American Festival & Pow Wow", "Stone Mountain Park", "1000 Robert E Lee Blvd", "Stone Mountain", "30083", "https://discoveratlanta.com/event/detail/native-american-festival-pow-wow/", corroborating_url="https://www.stonemountainpark.com/", start_date="2026-10-29", end_date="2026-11-01", subtype="cultural festival", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=2, hours=6, why_good="Dance, music, crafts and cultural interpretation offer a distinctive educational day.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Cabbagetown Chomp & Stomp", "Cabbagetown Park", "701 Kirkwood Ave SE", "Atlanta", "30316", "https://discoveratlanta.com/event/detail/cabbagetown-chomp-stomp/", start_date="2026-11-07", subtype="chili and music festival", price_level="free-entry", family=4, unique=4, evidence=4, value=4, urgency=2, hours=5, why_good="A lively neighborhood festival mixing food, music and outdoor community energy.", caveat="The event can be crowded and alcohol is present; choose daytime family hours.", indoor_outdoor="outdoor"),
    candidate("events-festivals-live-shows", "Everybody Loves Pirates", "Center for Puppetry Arts", "1404 Spring St NW", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/everybody-loves-pirates/", corroborating_url="https://puppet.org/", start_date="2026-10-01", end_date="2026-10-11", subtype="family puppet performance", price_level="paid", family=5, unique=5, evidence=4, value=4, urgency=2, hours=2.5, why_good="A playful pirate story in a uniquely Atlanta museum-and-theater setting.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Knock, Knock", "Alliance Theatre", "1280 Peachtree St NE", "Atlanta", "30309", "https://discoveratlanta.com/event/detail/knock-knock/", corroborating_url="https://www.alliancetheatre.org/", start_date="2026-11-14", end_date="2026-12-23", subtype="family theater", price_level="paid", family=5, unique=4, evidence=4, value=4, urgency=1, hours=2, why_good="A professionally produced family theater option for the holiday season.", indoor_outdoor="indoor"),
    candidate("events-festivals-live-shows", "Disney Worlds Collide Concert Tour", "State Farm Arena", "1 State Farm Dr", "Atlanta", "30303", "https://discoveratlanta.com/event/detail/disney-worlds-collide-concert-tour/", corroborating_url="https://www.statefarmarena.com/events", start_date="2026-11-30", subtype="family arena concert", price_level="paid", family=5, unique=5, evidence=4, value=3, urgency=1, hours=3, why_good="Disney Descendants, ZOMBIES and Camp Rock make a high-interest future arena show for many children.", indoor_outdoor="indoor"),
]


sports = [
    candidate("sports-live-games", "FIFA World Cup 26 Atlanta Semifinal", "Mercedes-Benz Stadium", "1 AMB Dr NW", "Atlanta", "30313", "https://www.mercedesbenzstadium.com/events/fifa-world-cup-26-tm---semi-final", corroborating_url="https://atlantafwc26.com/atlantas-final-match-schedule-for-the-fifa-world-cup-2026-now-available/", start_date="2026-07-15", start_time="15:00", subtype="live international soccer", price_level="premium-ticket", family=5, unique=5, evidence=5, value=2, hours=6, cost_note="Use official ticket channels only; total family cost can be very high.", why_good="A once-in-a-generation semifinal in Atlanta.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Atlanta Dream vs. Portland Fire", "Gateway Center Arena", "2330 Convention Center Concourse", "College Park", "30337", "https://dream.wnba.com/news/next-stop-dream-season-2026-atlanta-dream-announces-regular-season-schedule", start_date="2026-07-11", subtype="live WNBA basketball", price_level="paid", family=5, unique=5, evidence=5, value=4, hours=3, why_good="Women's professional basketball and the new Portland team create a strong family sports experience.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Atlanta Dream vs. Seattle Storm", "Gateway Center Arena", "2330 Convention Center Concourse", "College Park", "30337", "https://dream.wnba.com/schedule/", start_date="2026-07-12", start_time="20:00", subtype="live WNBA basketball", price_level="paid", family=5, unique=4, evidence=4, value=4, hours=3, why_good="A second vacation-window WNBA option with indoor comfort.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Gwinnett Stripers Disney Toy Story Night", "Gwinnett Field", "2500 Buford Dr", "Lawrenceville", "30043", "https://www.mlb.com/milb/gwinnett/news/homestand-highlights-stripers-start-their-engines-for-racing-night", start_date="2026-07-11", subtype="live Triple-A baseball", price_level="paid", family=5, unique=5, evidence=5, value=5, hours=4, why_good="Affordable baseball, a Toy Story theme and a giveaway are exceptionally child-friendly.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "Gwinnett Stripers Sunday Funday", "Gwinnett Field", "2500 Buford Dr", "Lawrenceville", "30043", "https://www.mlb.com/milb/gwinnett/news/homestand-highlights-stripers-start-their-engines-for-racing-night", start_date="2026-07-12", subtype="live Triple-A baseball", price_level="paid", family=5, unique=4, evidence=5, value=5, hours=4, why_good="Pre-game catch and kids run the bases make the family part of the action.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "Atlanta United 2 vs. Inter Miami CF II", "Turner Soccer Complex", "3200 George Busbee Pkwy NW", "Kennesaw", "30144", "https://www.atlutd.com/2/news/atlanta-united-2-announces-2026-mls-next-pro-regular-season-schedule", start_date="2026-07-11", subtype="live MLS NEXT Pro soccer", price_level="paid", family=5, unique=4, evidence=5, value=5, hours=3, why_good="An intimate and lower-cost match during Atlanta's biggest soccer month.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "FIFA Fan Festival Atlanta", "Centennial Olympic Park", "265 Park Ave W NW", "Atlanta", "30313", "https://atlantafwc26.com/fan-fest/", start_date="2026-07-11", end_date="2026-07-19", subtype="official big-screen soccer viewing", price_level="free-registration", family=5, unique=5, evidence=5, value=5, hours=5, why_good="Free official big-screen matches plus games and cultural programming.", caveat="Registration is mandatory for guests age 2 and older.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "All the Soccer Things at The Works", "The Works", "1295 Chattahoochee Ave NW", "Atlanta", "30318", "https://discoveratlanta.com/event/detail/all-the-soccer-things-at-the-works/", start_date="2026-07-11", end_date="2026-07-19", subtype="community soccer watch parties", price_level="free-entry", family=5, unique=5, evidence=5, value=5, hours=4, why_good="Match viewing, music, food and shopping offer flexibility for a family group.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "Celebration of Soccer & Sound", "Piedmont Park", "1320 Monroe Dr NE", "Atlanta", "30306", "https://www.axios.com/local/atlanta/2026/07/10/ludacris-world-cup-fifa-festival-piedmont-park", start_date="2026-07-19", start_time="11:00", subtype="World Cup final-day festival", price_level="free", family=5, unique=5, evidence=4, value=5, hours=6, why_good="A free large-scale closing celebration around the World Cup final.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "The LEGO Brand x FIFA Fan Fest", "Centennial Olympic Park", "265 Park Ave W NW", "Atlanta", "30313", "https://discoveratlanta.com/event/detail/the-lego-brand-x-fifa-fan-fest/", start_date="2026-07-11", end_date="2026-07-15", subtype="hands-on soccer activation", price_level="free-registration", family=5, unique=5, evidence=5, value=5, hours=3, why_good="Turns the global soccer event into a tactile building activity for children.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "Final Match World Soccer Block Party", "Yeppa & Co Buckhead", "306 Buckhead Ave NE", "Atlanta", "30305", "https://discoveratlanta.com/event/detail/final-match-world-soccer-block-party-at-yeppa-co/", start_date="2026-07-19", subtype="soccer block party", price_level="free-entry", family=4, unique=5, evidence=4, value=4, hours=4, why_good="Oversized screens deliver a lively alternative to the official downtown festival.", caveat="Confirm family hours and crowd conditions.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "College Football Hall of Fame", "College Football Hall of Fame", "250 Marietta St NW", "Atlanta", "30313", "https://www.cfbhall.com/", subtype="interactive sports museum", price_level="paid", family=5, unique=5, evidence=5, value=4, urgency=3, hours=3, why_good="Hands-on skill challenges and personalized team content work even for casual fans.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Mercedes-Benz Stadium Tour", "Mercedes-Benz Stadium", "1 AMB Dr NW", "Atlanta", "30313", "https://www.mercedesbenzstadium.com/stadium-tours", subtype="stadium behind-the-scenes tour", price_level="paid", family=5, unique=5, evidence=5, value=4, urgency=3, hours=2, why_good="Architecture, locker-room and field access turn the stadium into an experience without a game ticket.", caveat="Tour availability may be reduced around World Cup operations.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Truist Park Tour", "Truist Park", "755 Battery Ave SE", "Atlanta", "30339", "https://www.mlb.com/braves/ballpark/tours", subtype="ballpark behind-the-scenes tour", price_level="paid", family=5, unique=5, evidence=5, value=4, urgency=3, hours=2, why_good="A classic baseball experience that can pair with The Battery even while the Braves are away.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "Porsche Experience Center Atlanta", "Porsche Experience Center", "One Porsche Dr", "Atlanta", "30354", "https://www.porschedriving.com/atlanta", subtype="driving simulators and motorsport heritage", price_level="premium", family=4, unique=5, evidence=5, value=2, urgency=3, hours=3, why_good="Simulators, a heritage gallery and track views make a rare automotive sports day.", caveat="Driving programs have age and license requirements; younger children may be limited to exhibits and observation.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "Atlanta Motorsports Park Karting", "Atlanta Motorsports Park", "20 Duck Thurmond Rd", "Dawsonville", "30534", "https://www.atlantamotorsportspark.com/karting/", subtype="outdoor performance karting", price_level="paid", family=4, unique=5, evidence=5, value=3, urgency=3, hours=3, why_good="A highly regarded elevation-heavy kart circuit close to the north Georgia day-trip corridor.", caveat="Minimum age, height and skill rules apply.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "Andretti Indoor Karting & Games Buford", "Andretti Indoor Karting & Games", "2925 Buford Dr", "Buford", "30519", "https://andrettikarting.com/buford", subtype="indoor karting and games", price_level="paid", family=5, unique=4, evidence=5, value=3, urgency=3, hours=4, why_good="Karting, bowling, laser tag and games support mixed interests in one nearby building.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Andretti Indoor Karting & Games Marietta", "Andretti Indoor Karting & Games", "1255 Roswell Rd", "Marietta", "30062", "https://andrettikarting.com/marietta", subtype="indoor karting and games", price_level="paid", family=5, unique=4, evidence=5, value=3, urgency=3, hours=4, why_good="A second full-size indoor motorsport option that can pair with Marietta Square.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Topgolf Alpharetta", "Topgolf", "10900 Westside Pkwy", "Alpharetta", "30009", "https://topgolf.com/us/alpharetta/", subtype="technology-assisted golf games", price_level="paid", family=5, unique=4, evidence=5, value=4, urgency=3, hours=3, why_good="Very close, weather-protected hitting bays and game modes work for beginners.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "Topgolf Buford", "Topgolf", "2935 Buford Dr", "Buford", "30519", "https://topgolf.com/us/buford/", subtype="technology-assisted golf games", price_level="paid", family=5, unique=4, evidence=5, value=4, urgency=3, hours=3, why_good="A nearby golf-game option beside other Mall of Georgia activities.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "iFLY Indoor Skydiving Atlanta", "iFLY Atlanta", "2778 Cobb Pkwy SE", "Atlanta", "30339", "https://www.iflyworld.com/atlanta/", subtype="indoor skydiving", price_level="premium", family=5, unique=5, evidence=5, value=3, urgency=3, hours=2, why_good="A genuinely new flight experience with no airplane jump required.", caveat="Health, age and weight restrictions apply; book a flight time.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Stone Summit Kennesaw", "Stone Summit", "2801 George Busbee Pkwy NW", "Kennesaw", "30144", "https://www.ssclimbing.com/kennesaw", subtype="indoor rock climbing", price_level="paid", family=5, unique=4, evidence=5, value=4, urgency=3, hours=3, why_good="Large climbing walls offer a physical challenge with instruction and rental equipment.", caveat="Confirm youth supervision and belay policies.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Stone Summit Atlanta", "Stone Summit", "3701 Presidential Pkwy", "Atlanta", "30340", "https://www.ssclimbing.com/atlanta", subtype="indoor rock climbing", price_level="paid", family=5, unique=4, evidence=5, value=4, urgency=3, hours=3, why_good="Another major climbing gym with routes for a range of skill levels.", caveat="Confirm youth supervision and belay policies.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Cumming Aquatic Center", "Cumming Aquatic Center", "201 Aquatic Cir", "Cumming", "30040", "https://www.cummingaquaticcenter.com/", subtype="swimming and aquatic play", price_level="paid", family=5, unique=3, evidence=5, value=5, urgency=3, hours=3, why_good="The closest substantial swim facility is easy to fit into any hot day.", caveat="Check leisure-pool hours and capacity before leaving.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "Pickle and Social Gwinnett", "Pickle and Social", "2925 Buford Dr", "Buford", "30519", "https://pickleandsocial.com/gwinnett/", subtype="pickleball and social games", price_level="paid", family=4, unique=4, evidence=4, value=3, urgency=3, hours=3, why_good="Pickleball courts and casual games make an approachable new-sport outing.", caveat="Confirm junior play hours and court reservations.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "The Painted Pickle", "The Painted Pickle", "976 Brady Ave NW", "Atlanta", "30318", "https://thepaintedpickle.com/", subtype="pickleball and social games", price_level="paid", family=3, unique=4, evidence=4, value=3, urgency=3, hours=3, why_good="A polished pickleball experience near West Midtown attractions.", caveat="Some periods are adult-oriented; verify family hours.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Puttshack Atlanta", "Puttshack", "1115 Howell Mill Rd NW", "Atlanta", "30318", "https://www.puttshack.com/find-a-location/atlanta", subtype="technology mini golf", price_level="paid", family=5, unique=4, evidence=5, value=4, urgency=3, hours=2.5, why_good="Automated scoring and interactive holes turn mini golf into a video-game-like sport.", caveat="Later evening hours may be age-restricted.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Flight Club Atlanta", "Flight Club", "1055 Howell Mill Rd NW", "Atlanta", "30318", "https://flightclubdartsusa.com/atlanta", subtype="technology darts", price_level="paid", family=3, unique=4, evidence=5, value=3, urgency=3, hours=2, why_good="Automated darts games can work for families with older children.", caveat="Children must meet the venue's age and accompaniment rules; verify the time window.", age_notes="Best for ages 12 and older with adults.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "Your 3rd Spot", "Your 3rd Spot", "400 Chattahoochee Row NW", "Atlanta", "30318", "https://your3rdspot.com/atlanta/", subtype="multi-game social venue", price_level="paid", family=4, unique=5, evidence=5, value=3, urgency=3, hours=3, why_good="Bowling, hoops, curling, arcade games and more than 100 experiences solve mixed family preferences.", caveat="Verify family hours because evening access can be age-restricted.", indoor_outdoor="indoor"),
    candidate("sports-live-games", "LakePoint Sports Campus", "LakePoint Sports", "755 Hwy 293", "Emerson", "30137", "https://lakepointsports.com/", subtype="multi-sport tournament campus", price_level="event-dependent", family=4, unique=4, evidence=5, value=4, urgency=3, hours=4, why_good="A major regional sports complex with changing baseball, volleyball and other events.", caveat="Choose a specific public tournament or event before driving.", indoor_outdoor="mixed"),
    candidate("sports-live-games", "StationSoccer West End", "MARTA West End Station", "680 Lee St SW", "Atlanta", "30310", "https://www.soccerstreets.org/stationsoccer", subtype="community soccer facility", price_level="free-or-program", family=4, unique=5, evidence=4, value=5, urgency=3, hours=2, why_good="A unique transit-station soccer field demonstrates Atlanta's community soccer culture.", caveat="Confirm public-play or program access before visiting.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "Atlanta Silverbacks Park", "Atlanta Silverbacks Park", "3200 Atlanta Silverbacks Way", "Atlanta", "30340", "https://atlantasilverbacks.com/", subtype="soccer complex", price_level="event-dependent", family=4, unique=4, evidence=4, value=4, urgency=3, hours=3, why_good="A dedicated soccer complex close to the northeast metro corridor.", caveat="Select a public match, clinic or rental period before travel.", indoor_outdoor="outdoor"),
    candidate("sports-live-games", "The Battery Atlanta Plaza Experience", "The Battery Atlanta", "800 Battery Ave SE", "Atlanta", "30339", "https://batteryatl.com/events/", subtype="sports district and public programming", price_level="free-entry", family=5, unique=4, evidence=5, value=5, urgency=3, hours=4, why_good="Ballpark views, public events, stores and restaurants make a flexible sports-themed day even without a Braves home game.", indoor_outdoor="mixed"),
]


assert len(events) >= 50, len(events)
assert len(sports) >= 25, len(sports)

payload = {
    "metadata": {
        "checked_date": CHECKED,
        "home_reference": "7010 Brassfield Dr, Cumming, GA 30041",
        "methods": [
            "Official City of Cumming July 2026 calendar",
            "Discover Atlanta current family event listings and event detail pages",
            "Official venue and team schedules",
            "Atlanta FIFA World Cup 26 host committee and stadium sources",
        ],
        "pool_counts": {
            "events-festivals-live-shows": len(events),
            "sports-live-games": len(sports),
        },
        "limitations": [
            "Ticket inventory and weather can change after the checked date.",
            "Rows without published ratings keep rating fields null instead of inventing values.",
            "Official promotional images require attribution and are intended only for this private family-planning package.",
        ],
        "source_index": [
            CUMMING,
            DISCOVER,
            "https://atlantafwc26.com/fan-fest/",
            "https://www.mercedesbenzstadium.com/events/fifa-world-cup-26-tm---semi-final",
            "https://www.mlb.com/milb/gwinnett/news/homestand-highlights-stripers-start-their-engines-for-racing-night",
            "https://dream.wnba.com/news/next-stop-dream-season-2026-atlanta-dream-announces-regular-season-schedule",
            "https://www.atlutd.com/2/news/atlanta-united-2-announces-2026-mls-next-pro-regular-season-schedule",
        ],
    },
    "candidates": events + sports,
}

out = Path(__file__).resolve().parents[1] / "research" / "raw" / "events_sports.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"ok": True, "output": str(out), "events": len(events), "sports": len(sports)}))
