@startpacketdiag
colwidth = 16
scale_interval = 8
0-15: Source Port
16-31: Destination Port
32-63: Sequence Number
64-95: Acknowledgement Number
96-99: Header Length
100-105: Flags
106-111: Window
@endpacketdiag
