#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-an-llm",
  "--title",
  "What is an LLM",
  "--topic",
  "What is an LLM",
  "--output-id",
  "what-is-an-llm",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A large language model is a transformer-based neural network trained to predict text autoregressively.",
  "--fact",
  "Tokens are chunks of text rather than full words.",
  "--fact",
  "Newly generated tokens become part of the context for the next prediction.",
  "--fact",
  "Parameters are learned numeric weights inside the network.",
  "--fact",
  "Larger models often improve average capability, but size alone does not guarantee truth, reasoning quality, or cost efficiency.",
  "--fact",
  "Modern LLM inference usually depends on GPUs because transformers map well to parallel matrix operations.",
  "--anchor",
  "token stream",
  "--anchor",
  "context window box",
  "--anchor",
  "attention arcs",
  "--anchor",
  "autoregressive loop",
  "--anchor",
  "parameter counter",
  "--anchor",
  "capability versus truth warning",
  "--anchor",
  "GPU rack",
  "--anchor",
  "recap stack",
  "--system-label",
  "Prompt context",
  "--system-label",
  "Tokenizer",
  "--system-label",
  "Context window",
  "--system-label",
  "Transformer attention",
  "--system-label",
  "Parameter weights",
  "--system-label",
  "GPU compute",
  "--system-label",
  "Next token",
  "--system-label",
  "Feedback loop",
  "--system-label",
  "Capability trend",
  "--system-label",
  "Truth warning",
  "--system-label",
  "Recap stack"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
