#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-zero-padding-validation",
  "--title",
  "Zero Padding Gray Levels",
  "--topic",
  "Metro box hierarchy",
  "--output-id",
  "zero-padding-gray-levels",
  "--pattern",
  "layered-architecture",
  "--checked-date",
  "July 4, 2026",
  "--audience",
  "general technical viewers",
  "--duration",
  "4.0",
  "--fps",
  "6",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "Boxes must have zero internal padding.",
  "--fact",
  "Hierarchy levels must use different gray values.",
  "--anchor",
  "zero internal padding",
  "--anchor",
  "grayscale hierarchy levels",
  "--layer-label",
  "client",
  "--layer-label",
  "edge/API",
  "--layer-label",
  "application",
  "--layer-label",
  "domain service",
  "--layer-label",
  "data layer",
  "--layer-label",
  "platform",
  "--concern-label",
  "security policy",
  "--concern-label",
  "failure route",
  "--concern-label",
  "observability",
  "--concern-label",
  "rollout gate"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
