packet
  title Transport header arranged in 32-bit rows
  +16: "Source port"
  +16: "Destination port"
  +32: "Sequence number"
  +32: "Acknowledgment number"
  +4: "Data offset"
  +3: "Reserved"
  +1: "NS"
  +1: "CWR"
  +1: "ECE"
  +1: "URG"
  +1: "ACK"
  +1: "PSH"
  +1: "RST"
  +1: "SYN"
  +1: "FIN"
  +16: "Window size"
  +16: "Checksum"
  +16: "Urgent pointer"
  +32: "Options and padding"
