#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-zero-padding-wrapper-validation",
  "--title",
  "Zero Padding Wrapper Smoke",
  "--topic",
  "Metro hard-edge hierarchy",
  "--output-id",
  "zero-padding-wrapper",
  "--pattern",
  "layered-architecture",
  "--checked-date",
  "July 4, 2026",
  "--audience",
  "general technical viewers",
  "--duration",
  "4.0",
  "--fps",
  "6",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "Boxes must have zero internal padding.",
  "--fact",
  "Levels must be separated by grayscale value, not by padded interiors.",
  "--anchor",
  "zero internal padding",
  "--anchor",
  "grayscale hierarchy levels",
  "--layer-label",
  "input",
  "--layer-label",
  "planner",
  "--layer-label",
  "renderer",
  "--layer-label",
  "validator",
  "--layer-label",
  "audit",
  "--layer-label",
  "delivery",
  "--concern-label",
  "policy",
  "--concern-label",
  "failure route",
  "--concern-label",
  "observability",
  "--concern-label",
  "rollout"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
