architecture-beta
  group edge(cloud)[Edge]
  group core(cloud)[Core]
  service ingress(internet)[Ingress] in edge
  service api(server)[API] in core
  service worker(server)[Worker] in core
  service database(database)[Database] in core
  service queue(disk)[Queue] in core
  service archive(disk)[Archive] in core
  ingress:R --> L:api
  api:R --> L:worker
  worker:B --> T:database
  worker:R --> L:queue
  queue:B --> T:archive
