gantt
  title Gantt semantic roles
  dateFormat YYYY-MM-DD
  section Capacity
    Normal task :normal, 2026-01-01, 1d
    Active task :active, active_task, 2026-01-02, 1d
    Done task :done, done_task, 2026-01-03, 1d
    Critical task :crit, critical_task, 2026-01-04, 1d
    Active critical task :crit, active, active_critical, 2026-01-05, 1d
    Done critical task :crit, done, done_critical, 2026-01-06, 1d
