gitGraph
  commit id: "main"
  branch branch-01
  checkout branch-01
  commit id: "slot-01"
  checkout main
  branch branch-02
  checkout branch-02
  commit id: "slot-02"
  checkout main
  branch branch-03
  checkout branch-03
  commit id: "slot-03"
  checkout main
  branch branch-04
  checkout branch-04
  commit id: "slot-04"
  checkout main
  branch branch-05
  checkout branch-05
  commit id: "slot-05"
  checkout main
  branch branch-06
  checkout branch-06
  commit id: "slot-06"
  checkout main
  branch branch-07
  checkout branch-07
  commit id: "slot-07"
