ishikawa-beta
  Delivery delay
    Process
      Rework
      Handoffs
    People
      Training
      Ownership
    Platform
      Capacity
      Reliability
    Policy
      Approval
      Scheduling
