kanban
  slot01[Kanban slot 01]
    card01[Card 01]
  slot02[Kanban slot 02]
    card02[Card 02]
  slot03[Kanban slot 03]
    card03[Card 03]
  slot04[Kanban slot 04]
    card04[Card 04]
  slot05[Kanban slot 05]
    card05[Card 05]
  slot06[Kanban slot 06]
    card06[Card 06]
  slot07[Kanban slot 07]
    card07[Card 07]
  slot08[Kanban slot 08]
    card08[Card 08]
  slot09[Kanban slot 09]
    card09[Card 09]
  slot10[Kanban slot 10]
    card10[Card 10]
