sankey
Sankey node 01,Sankey node 02,8
Sankey node 02,Sankey node 03,7
Sankey node 03,Sankey node 04,6
Sankey node 04,Sankey node 05,5
Sankey node 05,Sankey node 06,4
Sankey node 06,Sankey node 07,3
Sankey node 07,Sankey node 08,2
