treemap-beta
  "Treemap capacity"
    "Treemap group 01"
      "Leaf 01": 12
    "Treemap group 02"
      "Leaf 02": 11
    "Treemap group 03"
      "Leaf 03": 10
    "Treemap group 04"
      "Leaf 04": 9
    "Treemap group 05"
      "Leaf 05": 8
    "Treemap group 06"
      "Leaf 06": 7
    "Treemap group 07"
      "Leaf 07": 6
    "Treemap group 08"
      "Leaf 08": 5
    "Treemap group 09"
      "Leaf 09": 4
    "Treemap group 10"
      "Leaf 10": 3
    "Treemap group 11"
      "Leaf 11": 2
