#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-a-skill",
  "--title",
  "What is a Skill",
  "--topic",
  "What is a Skill",
  "--output-id",
  "what-is-a-skill",
  "--pattern",
  "dependency-map",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A skill is a reusable capability package for specialized tasks.",
  "--fact",
  "A skill gives the harness structured instructions, scripts, and supporting resources.",
  "--fact",
  "Skills support progressive disclosure because they load when relevant instead of forcing long procedures into every prompt.",
  "--fact",
  "GitHub Copilot describes skills as folders of instructions, scripts, and resources.",
  "--fact",
  "Claude Code says long reference material in a skill costs almost nothing until it is needed.",
  "--fact",
  "OpenCode loads SKILL.md-based skills on demand.",
  "--fact",
  "Skills are useful for deploy checklists, debugging routines, architecture explainers, onboarding flows, and codebase maps.",
  "--fact",
  "The common mistake is making a skill too broad, verbose, or always relevant.",
  "--anchor",
  "skill card stack",
  "--anchor",
  "long prompt wall shrinking into one skill card",
  "--anchor",
  "compatible folder structures",
  "--anchor",
  "cost meter staying flat until activation",
  "--anchor",
  "example skill cards",
  "--anchor",
  "tool badges snapping onto the skill card",
  "--anchor",
  "bloated card being trimmed down",
  "--anchor",
  "progressive disclosure callout",
  "--dependency-label",
  "Trigger",
  "--dependency-label",
  "SKILL.md",
  "--dependency-label",
  "References",
  "--dependency-label",
  "Scripts",
  "--dependency-label",
  "Assets",
  "--dependency-label",
  "integration",
  "--dependency-label",
  "release gate",
  "--dependency-label",
  "fallback path",
  "--cluster-label",
  "Progressive disclosure",
  "--cluster-label",
  "Validation",
  "--cluster-label",
  "Tool instructions",
  "--cluster-label",
  "Runtime load",
  "--cluster-label",
  "Reusable workflow",
  "--cluster-label",
  "Scope boundary",
  "--cluster-label",
  "Cost control"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
