#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-design-contract-video",
  "--title",
  "Metro Design Contract Validation",
  "--topic",
  "strict Metro design adherence for video-generation skill validation",
  "--output-id",
  "metro-design-contract",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "6.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "The design must be a navigable modular megacanvas, not a title-and-cards slide.",
  "--fact",
  "Colorset1 is sufficient for the validation draft.",
  "--fact",
  "Square edges and zero internal padding are required for every box-like module.",
  "--fact",
  "Grayscale levels must carry hierarchy across visible surfaces.",
  "--fact",
  "Render-state validation must prove the late queue, retry, dead-letter, and feedback mechanisms.",
  "--anchor",
  "modular megacanvas",
  "--anchor",
  "queue fill",
  "--anchor",
  "worker activation",
  "--anchor",
  "retry branch",
  "--anchor",
  "dead-letter branch",
  "--anchor",
  "feedback throttle",
  "--anchor",
  "gray hierarchy levels",
  "--anchor",
  "square-edge modules",
  "--system-label",
  "Intake",
  "--system-label",
  "Event bus",
  "--system-label",
  "Signal",
  "--system-label",
  "Broker",
  "--system-label",
  "Queue",
  "--system-label",
  "Worker pool",
  "--system-label",
  "Store",
  "--system-label",
  "Retry policy",
  "--system-label",
  "Dead letter",
  "--system-label",
  "Throughput",
  "--system-label",
  "Throttle"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
