#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-a-guardrail",
  "--title",
  "What is a Guardrail",
  "--topic",
  "What is a Guardrail",
  "--output-id",
  "what-is-a-guardrail",
  "--pattern",
  "risk-bowtie",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A guardrail is a control layer around an agent, input, output, or tool action.",
  "--fact",
  "A guardrail decides whether a task should proceed, pause, be changed, or stop.",
  "--fact",
  "Guardrails can inspect user prompts, model outputs, and tool calls.",
  "--fact",
  "Guardrail actions include block, redact, route, and escalate.",
  "--fact",
  "A prompt suggests behavior, while a guardrail enforces a policy.",
  "--fact",
  "Google Model Armor can screen prompts and responses for prompt injection, jailbreaks, sensitive data, malicious URLs, and related risks.",
  "--fact",
  "OpenAI-style guidance uses automatic checks plus human review before sensitive or high-impact work continues.",
  "--fact",
  "For code assistants, common guardrails protect secrets, production systems, and destructive commands.",
  "--anchor",
  "shield gate around agent loop",
  "--anchor",
  "input gate",
  "--anchor",
  "output gate",
  "--anchor",
  "action gate",
  "--anchor",
  "prompt bubble versus hard gate",
  "--anchor",
  "Model Armor filter fan-out",
  "--anchor",
  "human approval control",
  "--anchor",
  "secrets and destructive command warnings",
  "--anchor",
  "safety versus friction balance",
  "--anchor",
  "residual risk block",
  "--threat-label",
  "Unsafe request",
  "--threat-label",
  "Prompt injection",
  "--threat-label",
  "Sensitive data",
  "--threat-label",
  "Destructive command",
  "--barrier-label",
  "Preventive barrier",
  "--barrier-label",
  "Policy gate",
  "--barrier-label",
  "Top event",
  "--barrier-label",
  "Allow",
  "--barrier-label",
  "Block",
  "--barrier-label",
  "Redact",
  "--barrier-label",
  "Escalate",
  "--barrier-label",
  "Human approval",
  "--barrier-label",
  "Mitigative barrier",
  "--consequence-label",
  "Consequence",
  "--consequence-label",
  "False positive friction",
  "--consequence-label",
  "Residual risk",
  "--consequence-label",
  "impact D"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
