#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Retain all isolated planning outcomes and the author's artifact critiques."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[3]
REVIEWS={
 'usefulcharts-theme-spark-1-20260912': 'Two real Bash tool errors, including a PowerShell command and a failed JSON check; Argo prompt bakes rightward engine streaks into the raster asset. Camera and lighting vary across subjects.',
 'usefulcharts-theme-spark-2-20260912': 'Portrait page conflicts with an ultra-wide background prompt; only Argo has a specific camera angle; Argo II prompt assumes modernized surfaces and changed geometry without photographs.',
 'usefulcharts-theme-spark-3-20260912': 'Argo includes a forward wake inside the image prompt. Argo II fallback requires silhouette variation before source photographs establish any design difference.',
 'usefulcharts-theme-b-spark-1-20260912': 'Raster trails are now excluded, but no shared camera is defined for all five assets and Argo II is assumed to belong to a sibling design lineage. Expansion count is inconsistent (95 additional versus 90 later).',
 'usefulcharts-theme-b-spark-2-20260912': 'The runtime skips the required thematic guide. Kestrel is prompted as faster than explorers and with motion blur; Argo II is forced to have structural variation; background/context enters individual asset prompts.',
 'usefulcharts-theme-b-spark-3-20260912': 'Shared camera/lighting and no-trail instructions improve. Argo II is still called next-generation and required to be a different design in a precondition; distinct hull identity does not establish either fact.'
}


def read(path):return json.loads(path.read_text(encoding='utf-8'))


def main():
    runs=[]
    for id,critique in REVIEWS.items():
        folder=ROOT/'evaluations/runs'/id
        manifest=read(folder/'run-manifest.json');event=read(folder/'event-check.json')
        result=read(folder/'evaluation-result.json');artifact=read(folder/'artifact-check.json')
        integrity=read(folder/'skill-integrity-check.json')
        promptpack=read(folder/'workspace/design/art-prompts.json')
        assert isinstance(promptpack,dict) and promptpack
        runs.append(dict(run_id=id,cohort='B' if '-b-' in id else 'A',model=manifest['pi'],payload=manifest['skill'],execution_pass=result['passed'],artifact_paths_pass=artifact['passed'],outputs=artifact['outputs'],payload_unchanged=integrity['passed'],observed_models=event['observedModels'],read_paths=[c['path'] for c in event['calls'] if c.get('path')],tool_errors=[c for c in event['calls'] if c.get('isError')],artifact_review=dict(status='fail',classification='agent',critique=critique),complete_pass=False))
    summary=dict(date='2026-09-12',case='Naturalistic planning-only theme and image-prompt preparation',model='gpt-5.3-codex-spark',runtime_payloads_unchanged=all(r['payload_unchanged'] for r in runs),execution_passes=sum(r['execution_pass'] for r in runs),complete_passes=0,total_runs=len(runs),runs=runs,limitation='No images are generated by these tests; no final-art quality or model ranking is inferred.')
    target=ROOT/'evaluations/usefulcharts-style/thematic-art-direction-summary-20260912.json'
    target.write_text(json.dumps(summary,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({k:v for k,v in summary.items() if k!='runs'}))


if __name__=='__main__':main()
