#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Write the compact evidence inventory for the six diagram/presentation skills."""
import hashlib
import json
import subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
SKILLS=['mermaid','plantuml-colorset-renderer','echarts-animated-svg','slidev-echarts','slidev-animejs','slidev-quality-audit']
EXCLUDED={'skills/mermaid/references/diagram-selection.md','skills/echarts-animated-svg/references/chart-animation-profiles.md','skills/slidev-animejs/references/integration-patterns.md'}
PREEXISTING=[f'skills/{skill}/SKILL.md' for skill in SKILLS]+['skills/mermaid/scripts/animate_mermaid_svg.py','skills/slidev-echarts/references/integration-patterns.md']
def git_paths(command):
    return subprocess.check_output(['git','-c','core.safecrlf=false',*command,'--',*[f'skills/{skill}' for skill in SKILLS]],cwd=ROOT,text=True).splitlines()
changed=sorted((set(git_paths(['diff','--name-only']))|set(git_paths(['ls-files','--others','--exclude-standard'])))-EXCLUDED)
runs={
 'mermaid':'20261002-colorset-mermaid-luna-3',
 'plantuml-colorset-renderer':'20261002-colorset-plantuml-luna-7',
 'echarts-animated-svg':'20261002-colorset-echarts-luna-5',
 'slidev-echarts':'20261002-colorset-slidev-echarts-luna-4',
 'slidev-animejs':'20261002-colorset-slidev-animejs-luna-2',
 'slidev-quality-audit':'20261002-colorset-slidev-quality-luna-2',
}
routes={
 'mermaid':{'outputs':['authored MMD/Markdown fences and style/check JSON','renderer static SVG','faithful animated SVG from newly rendered source','animated SVG from existing SVG (palette gate)','HTML replay galleries and browser/raster/downstream captures'], 'authoredPaths':['assets/themes/*.json','assets/themes/*.css','assets/examples/mermaid-max-complexity/gallery.css','assets/examples/mermaid-max-complexity/svg/colorset1/*.svg','assets/examples/mermaid-max-complexity/svg/colorset2/*.svg','assets/examples/mermaid-max-elements/index.html'], 'modes':{'default':'colorset1','fullColorVariant':'colorset2','metadata':'colorset directives and data-colorset SVG','sourceFidelity':'existing source facts and embedded images are immutable; off-palette existing SVG is rejected'}, 'changes':['normalize native/default CSS including named colors and drop shadows after rendering','reject incompatible prerendered SVG before animation','exact-file styler targeting prevents reading/writing copied skill examples','normalize all canonical gallery SVG paints and refresh SHA256 pairs','normalize gallery chrome'], 'openGaps':['No fresh complete62-render layout regeneration; existing124 canonical outputs normalized without geometry changes and full gallery validation passed. Arbitrary unedited external source SVG must be restyled explicitly before import.']},
 'plantuml-colorset-renderer':{'outputs':['authored PlantUML source and optional themed-source','SVG render via CLI/server/Kroki','PNG render including Ditaa and standalone math/LaTeX','batch render report and coverage metadata','HTML family galleries'], 'authoredPaths':['assets/themes/*.puml','assets/examples/plantuml-colorset-renderer*/svg/*.svg','assets/examples/plantuml-colorset-renderer*/png/*.png','assets/examples/plantuml-colorset-renderer*/*.css'], 'modes':{'default':'colorset1','categoryVariant':'colorset2','metadata':'data-colorset, report.colorset, palette_normalized and source_media_preserved','sourceFidelity':'quoted and colon-introduced data/labels preserved; original source input unchanged; narrow imported image/sprite PNG boundary'}, 'changes':['default renderer and theme now colorset1','normalize SVG actual paint even after source/custom theme overrides','quantize non-source-media PNG including theme-incompatible Ditaa/math/LaTeX','normalize explicit source presentation syntax without rewriting fact-bearing labels','report validator rejects all undeclared SVG paints and all non-source-media PNG RGB values'], 'openGaps':['chronology is upstream-unavailable in frozen PlantUML1.2026.6 coverage,29 fixtures/28 available output fixtures','source-media PNGs preserve source pixels; authored chrome requires matching SVG/editable source inspection, not a blanket raster palette pass']},
 'echarts-animated-svg':{'outputs':['SVGRenderer/SSR chart SVG','animated SVG','HTML replay gallery with focus/hover/replay/expand states','small static bar SVG runtime template','JSON animation pair validation','optional downstream browser raster/GIF/video capture'], 'authoredPaths':['assets/templates/static-bar-chart.svg','assets/templates/echarts-colorsets.mjs (exported paints; CSS decoder lookup is input data)','assets/examples/echarts-animated-svg/index.html','assets/examples/echarts-animated-svg/scripts/build-gallery.mjs'], 'modes':{'default':'colorset1','gallery':'colorset2 (43 charts distinguish independent categories)','metadata':'selected helper argument and gallery rationale','sourceFidelity':'imported SVG image pixels only; existing off-palette authored chart SVG rejected'}, 'changes':['self-contained exact theme/option/SVG/Canvas helper','discrete visualMap bins and gradient endpoints preserve values/geometry','normalize defaults, hover CSS and tween base paints','bar template now red/neutral cs1','animator and pair validator reject off-palette actual paint'], 'openGaps':['Imported input chart must be palette-compliant before animation. Canvas-only arbitrary user color functions/images require source boundary and renderer inspection.']},
 'slidev-echarts':{'outputs':['responsive Vue SVGRenderer/CanvasRenderer chart','hover/tooltips/legend/emphasis states and click transitions','custom dashboard/SVG motion','built HTML deck','PDF/PNG/video export from deck','chart options/data JSON'], 'authoredPaths':['assets/templates/echarts-colorsets.mjs (exported paints; CSS decoder lookup is input data)','assets/examples/slidev-echarts/components/*.vue','assets/examples/slidev-echarts/lib/chart-lab.js','assets/examples/slidev-echarts/styles/*.css','assets/examples/slidev-echarts/slides.md'], 'modes':{'default':'colorset1','fixture':'colorset2 (multivariate chart/category demonstration)','metadata':'helper selected colorset and contract','sourceFidelity':'only original imported image/logo pixels; wrappers and labels remain checked'}, 'changes':['responsive wrapper selects exact theme and attaches palette enforcement before setOption','normalize options, hover defaults and Canvas/SVG tween paints','replace off-palette authored CSS/SVG/chart literals','override default Slidev code background with exact neutral'], 'openGaps':['The full audit inspects DOM/SVG click states; Canvas base paints additionally use setter/option enforcement. No fresh PDF/video encode was generated in this pass.','Two existing density warnings remain on slide31; zero error/palette findings.']},
 'slidev-animejs':{'outputs':['Vue CSS/DOM/SVG animations across30 slides','six standalone editable SVG assets','runtime SVG Vue asset pack','hover/click/timeline/morph/stagger states','built HTML deck and downstream PDF/PNG/video export'], 'authoredPaths':['assets/templates/slidev-svg-asset-pack/assets/animated-svg/*.svg','assets/templates/slidev-svg-asset-pack/components/*.vue','assets/examples/slidev-animejs/components/*.vue','assets/examples/slidev-animejs/styles/*.css','assets/examples/slidev-animejs/slides.md'], 'modes':{'default':'colorset1','fixtureAndRuntimePack':'colorset2 (separate demonstration mechanisms)','metadata':'runtime pack declared colorset and palette selection report','sourceFidelity':'imported original artwork only; authored animation paints and chrome stay exact'}, 'changes':['repair authored literals and derived CSS gradient endpoint choices','step categorical colors with imported Anime.js steps(1), preserving smooth geometry/opacity','fix six SVG data-allow-hidden attributes to valid XML','exact code background and stronger neutral label contrast'], 'openGaps':['No fresh PDF/video encode was generated in this pass; final source/builds and all93 click states were checked.']},
 'slidev-quality-audit':{'outputs':['JSON/Markdown quality reports (nonvisual metadata)','browser screenshots of supplied deck states (source evidence)','DOM/SVG authored paint audit findings'], 'authoredPaths':['scripts/audit-slidev-quality.ts (computed palette gate)','assets/palettes/colorsets.json'], 'modes':{'default':'colorset1','explicitAudit':'colorset2','metadata':'--colorset CLI flag','sourceFidelity':'screenshots are observed evidence; narrow data-source-media marker only'}, 'changes':['load exact local allowlist with selected CLI option','off-palette-paint error gate for visible computed DOM/SVG paint','document source-media boundary and Canvas/gradient/pseudo-element limits'], 'openGaps':['Isolated pi case is a planning-only contract case; independent local full deck browser checks verify actual execution. It is not an isolated full deck runtime acceptance case.','Computed-style gate does not prove arbitrary Canvas pixels, all pseudo-elements or all gradient endpoints; inspect editable paints and rendered exports.']},
}
routes['mermaid']['authoredPaths']=[path for path in routes['mermaid']['authoredPaths'] if not path.startswith('assets/themes/')]
routes['mermaid']['authoredPaths'].insert(0,'scripts/style_mermaid_directory.py (generated theme contracts)')
routes['mermaid']['changes'].append('preserve url gradient/filter IDs and reject unsupported paint syntax and off-palette SMIL color values')
routes['echarts-animated-svg']['changes'].append('resolve native chord SVG API sentinel source/target/auto into an exact rendered neutral paint')
routes['slidev-echarts']['changes'].append('resolve serialized SVG API paint sentinels while leaving editable source-role semantics intact')
def read_json(path):
    return json.loads(path.read_text(encoding='utf-8')) if path.exists() else None
inventory=[]
for skill in SKILLS:
    run=ROOT/'evaluations/runs'/runs[skill]
    manifest=read_json(run/'run-manifest.json')
    result=read_json(run/'evaluation-result.json')
    inventory.append({'skill':skill,**routes[skill],'sourceFidelityPaths':['imported <image>/data-source-media leaf assets only'],'changedPaths':[path for path in changed if path.startswith(f'skills/{skill}/')],'testedRuntime':{'runId':runs[skill],'classification':'contract-smoke; planning-only' if skill=='slidev-quality-audit' else 'contract-smoke','model':'openai-codex/gpt-5.6-luna','profile':'runtime','strict':True,'passed':result.get('passed') if result else None,'requiredOutputs':manifest.get('expectedOutputs') if manifest else None,'command':(run/'command.txt').read_text(encoding='utf-8') if (run/'command.txt').exists() else None,'result':str((run/'evaluation-result.json').relative_to(ROOT)).replace('\\','/')}})
hashes=[]
for skill in ['mermaid','plantuml-colorset-renderer']:
    for path in (ROOT/'skills'/skill/'assets/examples').rglob('*.svg'):
        if 'node_modules' in path.parts: continue
        hashes.append({'path':path.relative_to(ROOT).as_posix(),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
commands=[
 {'command':'uv run --script projects/colorset-audit/scripts/test-diagram-palettes.py','result':'pass4 tests: negative gates, source fact preservation, all178 published SVG palette checks'},
 {'command':'node --experimental-strip-types projects/colorset-audit/scripts/test-chart-colors.ts','result':'pass both independent templates; named/RGB/RGBA/HSL/alpha, gradient endpoints, discrete scales, data/labels'},
 {'command':'uv run --script projects/colorset-audit/scripts/check-diagram-preservation.py','result':'pass178 SVGs retain geometry attributes, IDs, hierarchy, labels and image references; inline style excluded'},
 {'command':'python skills/mermaid/assets/examples/mermaid-max-elements/scripts/test_max_elements.py','result':'pass12 tests'},
 {'command':'python skills/mermaid/assets/examples/mermaid-max-complexity/scripts/test_gallery.py','result':'pass8 tests'},
 {'command':'python skills/mermaid/assets/examples/mermaid-max-complexity/scripts/validate_gallery.py','result':'pass31 families,62 sources/static-animated pairs,124 SVG outputs'},
 {'command':'uv run --script skills/plantuml-colorset-renderer/scripts/test_plantuml_coverage.py','result':'pass19 tests'},
 {'command':'uv run --script skills/plantuml-colorset-renderer/scripts/validate_plantuml_coverage.py --fixtures skills/plantuml-colorset-renderer/assets/examples/base --report skills/plantuml-colorset-renderer/assets/examples/plantuml-colorset-renderer/render-report.json --report skills/plantuml-colorset-renderer/assets/examples/plantuml-colorset-renderer-cs1/render-report.json --gallery skills/plantuml-colorset-renderer/assets/examples/plantuml-colorset-renderer --gallery skills/plantuml-colorset-renderer/assets/examples/plantuml-colorset-renderer-cs1','result':'pass27 canonical+1 release-extra families,29 fixtures,28 published fixtures'},
 {'command':'uv run --script skills/plantuml-colorset-renderer/scripts/validate_plantuml_render_report.py --report <gallery>/render-report.json --output <gallery> --colorset <colorset1|colorset2> --coverage-manifest skills/plantuml-colorset-renderer/references/diagram-types.json','result':'pass both galleries; actual SVG and non-source-media PNG paints'},
 {'command':'uv run --script skills/echarts-animated-svg/scripts/test_validate_animated_svg.py','result':'pass2 tests'},
 {'command':'npm run build / npm run verify','cwd':'skills/echarts-animated-svg/assets/examples/echarts-animated-svg','result':'pass43 chart cards,43 SVGs, screenshot manually inspected'},
 {'command':'npx slidev build --base ./ --router-mode hash --out ../../../../../projects/colorset-audit/artifacts/html/<skill>','cwd':'skills/<slidev-echarts|slidev-animejs>/assets/examples/<skill>','result':'pass both; transitive Rolldown PURE annotation warnings retained'},
 {'command':'npx tsx skills/slidev-quality-audit/scripts/audit-slidev-quality.ts --deck skills/slidev-echarts/assets/examples/slidev-echarts --out projects/colorset-audit/artifacts/reviews/slidev-echarts-final --colorset colorset2 --strict --screenshots issues','result':'pass36 slides/129 states,zero errors,two density warnings'},
 {'command':'npx tsx skills/slidev-quality-audit/scripts/audit-slidev-quality.ts --deck skills/slidev-animejs/assets/examples/slidev-animejs --out projects/colorset-audit/artifacts/reviews/slidev-animejs-verified --colorset colorset2 --strict --screenshots issues','result':'pass30 slides/93 states,zero findings'},
 {'command':'uv run --script scripts/summarize-pi-json-events.py evaluations/runs/<run>/events.jsonl --require-model gpt-5.6-luna --fail-on-invalid-json --fail-on-tool-error --output projects/colorset-audit/artifacts/reviews/<run>-trace.json','result':'pass final traces; inspect exact isolated expected-output lists above'},
 {'command':'git -c core.safecrlf=false diff --check -- skills/mermaid skills/plantuml-colorset-renderer skills/echarts-animated-svg skills/slidev-echarts skills/slidev-animejs skills/slidev-quality-audit','result':'pass'},
]
failures=[
 {'runs':['20261002-colorset-slidev-animejs-spark-1','20261002-colorset-slidev-echarts-spark-1','20261002-colorset-slidev-quality-spark-1'],'classification':'infrastructure','reason':'Spark unsupported for ChatGPT account; provider rejects before any tool. New Luna exception required for the three Slidev skills.'},
 {'runs':['20261002-colorset-mermaid-luna-1'],'classification':'skill-design','reason':'Directory-wide styling scanned copied skill Markdown, modified four references, and caused three tool errors. Repaired by exact source-file support and narrowed task-source guidance; luna2 clean strict pass.'},
 {'runs':['20261002-colorset-echarts-luna-3','20261002-colorset-plantuml-luna-3'],'classification':'evaluator-invocation','reason':'Harness expected filenames differed from exact prompt paths. Correct artifacts were produced; strict missing-path gate correctly failed. Rerun with exact prompts/expected paths passed.'},
 {'commands':['First PlantUML validation used nonexistent coverage-manifest.json instead of diagram-types.json','First ECharts unit invocation used nonexistent test_animate_echarts_svg.py instead of test_validate_animated_svg.py','First independent ECharts pair validator used stagger60 rather than produced90ms'],'classification':'evaluator-invocation','reason':'Corrected commands passed; these initial failures are not hidden or counted as skill passes.'},
 {'classification':'deterministic/browser-development','reason':'Initial checks exposed unnamed native paints, rgba hover paints, continuous categorical Anime.js hues, code background defaults, SVG boolean XML syntax, and a low-contrast label. All were repaired and rerun; final results above.'},
 {'classification':'deterministic-fixture-maintenance','reason':'After tightening PNG validation even without palette_normalized metadata, a legacy signature-only fake PNG fixture and missing Pillow test dependency failed. Replaced it with a real exact-palette PNG, added Pillow test metadata, asserted rejection of an off-palette replacement, and made malformed PNG decoding a structured finding. All19 tests pass.'},
]
project_names=['audit-diagram-colors.py','repair-diagram-literals.py','document-diagram-contracts.py','normalize-published-diagrams.py','refresh-diagram-reports.py','repair-mermaid-chrome.py','expand-css-colors.py','expand-js-css-colors.py','test-diagram-palettes.py','test-chart-colors.ts','check-diagram-preservation.py','write-diagram-audit.py']
document={'schemaVersion':1,'date':'2026-10-02','executedUtcDate':'2026-10-03','claim':'Supported output-route audit and actual paint repairs; not an exhaustive proof of arbitrary authored scenes or release cohort validation. No skill marked done.','canonicalPalette':'skills/hyperframes-explainer/assets/palettes/colorsets.json (read-only baseline copied independently into all six bundles)','skills':inventory,'testedCommands':commands,'independentRootChecker':{'report':'projects/colorset-audit/artifacts/reviews/diagram-root-checker.json','artifactCount':185,'findings':0,'scope':'178 published Mermaid/PlantUML SVGs,6 Anime runtime SVGs,43-chart ECharts HTML gallery','invocation':'uv run --script scripts/validate-colorsets.py --input <each individual svg> --input skills/echarts-animated-svg/assets/examples/echarts-animated-svg/index.html --report projects/colorset-audit/artifacts/reviews/diagram-root-checker.json'},'failures':failures,'allChangedSkillPaths':changed,'preexistingMixedFilesPreserved':PREEXISTING,'untouchedPreexistingFilesExcluded':sorted(EXCLUDED),'auditProjectScripts':[f'projects/colorset-audit/scripts/{name}' for name in project_names],'publishedSvgHashes':hashes,'publicationRequired':['mermaid-max-complexity','plantuml-colorset-renderer','plantuml-colorset-renderer-cs1','echarts-animated-svg','slidev-echarts','slidev-animejs'],'publicationOwner':'root agent; no staging/commit/push performed by this subagent','publicationReview':'evaluations/colorset-audit/diagram-publication-20261002.md'}
out=ROOT/'evaluations/colorset-audit/diagrams-20261002.json'
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(json.dumps(document,indent=2)+'\n',encoding='utf-8')
print(f'Wrote {out.relative_to(ROOT)}: {len(changed)} touched skill paths, {len(hashes)} exact SVG hashes.')
