' plantuml-colorset-renderer: cs1 custom theme
skinparam backgroundColor #ffffff
skinparam shadowing false
skinparam DefaultFontName Arial
skinparam DefaultFontColor #000000
skinparam ArrowColor #696969
skinparam RoundCorner 6
skinparam TitleFontColor #000000
skinparam NoteBackgroundColor #9e1b32
skinparam NoteBorderColor #9e1b32
skinparam NoteBorderThickness 0
skinparam NoteFontColor #ffffff
skinparam SequenceParticipantBackgroundColor #333e48
skinparam SequenceParticipantBorderColor #333e48
skinparam SequenceParticipantBorderThickness 0
skinparam SequenceParticipantFontColor #ffffff
skinparam UsecaseBackgroundColor #6d1222
skinparam UsecaseBorderColor #6d1222
skinparam UsecaseBorderThickness 0
skinparam UsecaseFontColor #ffffff
skinparam ClassBackgroundColor #828282
skinparam ClassBorderColor #828282
skinparam ClassBorderThickness 0
skinparam ClassFontColor #000000
skinparam ObjectBackgroundColor #e8002a
skinparam ObjectBorderColor #e8002a
skinparam ObjectBorderThickness 0
skinparam ObjectFontColor #ffffff
skinparam ActivityBackgroundColor #4f4f4f
skinparam ActivityBorderColor #4f4f4f
skinparam ActivityBorderThickness 0
skinparam ActivityFontColor #ffffff
skinparam ActivityDiamondBackgroundColor #696969
skinparam ActivityDiamondBorderColor #696969
skinparam ActivityDiamondBorderThickness 0
skinparam ActivityDiamondFontColor #ffffff
skinparam ComponentBackgroundColor #9c9c9c
skinparam ComponentBorderColor #9c9c9c
skinparam ComponentBorderThickness 0
skinparam ComponentFontColor #000000
skinparam InterfaceBackgroundColor #b5b5b5
skinparam InterfaceBorderColor #b5b5b5
skinparam InterfaceBorderThickness 0
skinparam InterfaceFontColor #000000
skinparam NodeBackgroundColor #1c1c1c
skinparam NodeBorderColor #1c1c1c
skinparam NodeBorderThickness 0
skinparam NodeFontColor #ffffff
skinparam DatabaseBackgroundColor #363636
skinparam DatabaseBorderColor #363636
skinparam DatabaseBorderThickness 0
skinparam DatabaseFontColor #ffffff
skinparam CloudBackgroundColor #000000
skinparam CloudBorderColor #000000
skinparam CloudBorderThickness 0
skinparam CloudFontColor #ffffff
skinparam QueueBackgroundColor #cfcfcf
skinparam QueueBorderColor #cfcfcf
skinparam QueueBorderThickness 0
skinparam QueueFontColor #000000
skinparam StateBackgroundColor #e7e7e7
skinparam StateBorderColor #e7e7e7
skinparam StateBorderThickness 0
skinparam StateFontColor #000000
skinparam ClassHeaderBackgroundColor #828282
skinparam SequenceActorBackgroundColor #ffffff
skinparam SequenceActorBorderColor #333e48
skinparam SequenceActorFontColor #000000
skinparam SequenceLifeLineBorderColor #696969
skinparam SequenceArrowColor #696969
skinparam ActorBackgroundColor #ffffff
skinparam ActorBorderColor #333e48
skinparam ActorFontColor #000000
skinparam ActivityStartColor #333e48
skinparam ActivityEndColor #e8002a
skinparam StateStartColor #333e48
skinparam StateEndColor #e8002a
skinparam TimingBackgroundColor #ffffff
skinparam TimingFontColor #000000
skinparam TimingLineColor #696969
skinparam LegendBackgroundColor #ffffff
skinparam LegendBorderColor #ffffff
skinparam LegendBorderThickness 0
<style>
title {
  LineThickness 0
  BackgroundColor transparent
}
root {
  Padding 6
  FontColor #000000
  LineColor #696969
  BackgroundColor #ffffff
}
arrow {
  LineThickness 1.5
  LineColor #696969
  FontColor #000000
}
actor {
  LineColor #333e48
  FontColor #000000
  BackGroundColor #ffffff
}
node, artifact, folder, frame, rectangle, card {
  FontColor #ffffff
  LineColor #1c1c1c
  LineThickness 0
  BackGroundColor #1c1c1c
}
component, interface {
  FontColor #000000
  LineColor #9c9c9c
  LineThickness 0
  BackGroundColor #9c9c9c
}
database, storage, collections {
  FontColor #ffffff
  LineColor #363636
  LineThickness 0
  BackGroundColor #363636
}
cloud {
  FontColor #ffffff
  LineColor #000000
  LineThickness 0
  BackGroundColor #000000
}
queue {
  FontColor #000000
  LineColor #cfcfcf
  LineThickness 0
  BackGroundColor #cfcfcf
}
agent, participant {
  FontColor #ffffff
  LineColor #333e48
  LineThickness 0
  BackGroundColor #333e48
}
class {
  FontColor #000000
  LineColor #828282
  LineThickness 0
  BackGroundColor #828282
}
diamond {
  FontColor #ffffff
  LineColor #696969
  LineThickness 0
  BackGroundColor #696969
}
note {
  FontColor #ffffff
  LineColor #9e1b32
  LineThickness 0
  BackGroundColor #9e1b32
}
activity {
  FontColor #ffffff
  LineColor #4f4f4f
  LineThickness 0
  BackGroundColor #4f4f4f
}
state {
  FontColor #000000
  LineColor #e7e7e7
  LineThickness 0
  BackGroundColor #e7e7e7
}
chartDiagram {
  BackGroundColor #ffffff
  FontColor #000000
  axis {
    LineColor #696969
    FontColor #000000
  }
  grid {
    LineColor #e7e7e7
  }
  bar {
    LineColor #9e1b32
    BackGroundColor #9e1b32
    LineThickness 0
  }
  line {
    LineColor #333e48
  }
  scatter {
    MarkerColor #6d1222
  }
}
activityDiagram {
  arrow {
    LineColor #696969
    LineThickness 1.5
  }
}
</style>
