@startditaa
+-----------+       +-----------+
| Request   |------>| API       |
| {io}      |       | {s}       |
+-----------+       +-----+-----+
                          |
                    +-----v-----+
                    | Document  |
                    | {d}       |
                    +-----------+
@endditaa
