@startnwdiag
title Network
network dmz {
  address = "10.0.0.0/24";
  web01 [address = "10.0.0.10"];
  web02 [address = "10.0.0.11"];
}
network internal {
  address = "10.0.1.0/24";
  web01 [address = "10.0.1.10"];
  db [address = "10.0.1.20"];
}
@endnwdiag
