#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-zero-padding-validation/data-lineage-smoke",
  "--title",
  "Data Lineage Zero Padding",
  "--topic",
  "Lineage boxes without internal decoration",
  "--output-id",
  "data-lineage-zero-padding",
  "--pattern",
  "data-lineage",
  "--checked-date",
  "July 4, 2026",
  "--audience",
  "general technical viewers",
  "--duration",
  "4.0",
  "--fps",
  "6",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "Lineage boxes use grayscale level fills.",
  "--fact",
  "Inactive boxes do not use internal padded decoration.",
  "--anchor",
  "zero internal padding",
  "--anchor",
  "gray lineage levels",
  "--lineage-label",
  "source",
  "--lineage-label",
  "normalize",
  "--lineage-label",
  "transform",
  "--lineage-label",
  "validate",
  "--lineage-label",
  "publish",
  "--lineage-label",
  "consume",
  "--quality-label",
  "schema gate",
  "--quality-label",
  "drift",
  "--quality-label",
  "rollback",
  "--quality-label",
  "rollback plan"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
