#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-an-agent",
  "--title",
  "What is an Agent",
  "--topic",
  "What is an Agent",
  "--output-id",
  "what-is-an-agent",
  "--pattern",
  "state-machine",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "An agentic system combines a model with tools, state or memory, and orchestration.",
  "--fact",
  "An agent does more than answer once: it can observe context, take actions, inspect results, and continue in a loop.",
  "--fact",
  "A minimal teaching decomposition is context, environment, actions, and a loop or policy.",
  "--fact",
  "Context can include chat history, files, instructions, memory, and tool outputs.",
  "--fact",
  "Environment is the system the agent can inspect or affect, such as a repo, terminal, browser, ticket system, docs, or database.",
  "--fact",
  "Actions can include reading files, running tests, searching docs, calling APIs, or asking for approval.",
  "--fact",
  "The loop or policy decides whether to keep exploring, execute a tool, or stop.",
  "--fact",
  "A workflow follows predefined steps, while an agent adapts based on what it finds.",
  "--anchor",
  "agent loop ring",
  "--anchor",
  "Observe / Act / Check / Continue loop",
  "--anchor",
  "four labeled component cards",
  "--anchor",
  "stacked context panes",
  "--anchor",
  "environment blocks for repo, terminal, browser, tickets, docs, and database",
  "--anchor",
  "tool icons around the loop",
  "--anchor",
  "policy decision fork",
  "--anchor",
  "fixed workflow lane",
  "--anchor",
  "adaptive agent lane",
  "--anchor",
  "final Model + Tools + State + Loop badge",
  "--state-label",
  "observe",
  "--state-label",
  "context",
  "--state-label",
  "action",
  "--state-label",
  "check",
  "--state-label",
  "continue",
  "--state-label",
  "stop",
  "--guard-label",
  "tool permission",
  "--guard-label",
  "state memory",
  "--guard-label",
  "environment result"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
