---
# mermaid: config begin
config:
  theme: "base"
  themeVariables:
    background: "#ffffff"
    primaryColor: "#9e1b32"
    primaryTextColor: "#ffffff"
    primaryBorderColor: "#9e1b32"
    secondaryColor: "#000000"
    secondaryTextColor: "#ffffff"
    secondaryBorderColor: "#000000"
    tertiaryColor: "#828282"
    tertiaryTextColor: "#000000"
    tertiaryBorderColor: "#828282"
    lineColor: "#696969"
    textColor: "#333e48"
    mainBkg: "#9e1b32"
    nodeBkg: "#9e1b32"
    nodeBorder: "#9e1b32"
    clusterBkg: "#e7e7e7"
    clusterBorder: "#9c9c9c"
    defaultLinkColor: "#696969"
    edgeLabelBackground: "#ffffff"
    labelColor: "#ffffff"
    titleColor: "#333e48"
    emUiFill: "#9e1b32"
    emUiStroke: "#9e1b32"
    emProcessorFill: "#000000"
    emProcessorStroke: "#000000"
    emReadModelFill: "#828282"
    emReadModelStroke: "#828282"
    emCommandFill: "#1c1c1c"
    emCommandStroke: "#1c1c1c"
    emEventFill: "#9c9c9c"
    emEventStroke: "#9c9c9c"
    emArrowhead: "#9e1b32"
    emRelationStroke: "#696969"
  themeCSS: ".node > rect, .node > circle, .node > ellipse, .node > polygon, .node > path, rect.actor, .note, .task, .task0, .task1, .task2, .task3 { stroke-width: 0 !important; }"
# mermaid: config end
# mermaid: metadata begin
mermaid:
  colorset: "colorset1"
  mode: "standard"
  palette: "basic-red-neutral-style"
# mermaid: metadata end
---
eventmodeling
  tf 01 ui UserInterface
  tf 02 pcr Processor
  tf 03 rmo ReadModel
  tf 04 cmd Command
  tf 05 evt Event
