#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-square-composition-validation",
  "--title",
  "Metro Square Composition Validation",
  "--topic",
  "aligned queue pressure and retry control in an event pipeline",
  "--output-id",
  "metro-square-composition",
  "--pattern",
  "systems-flow",
  "--checked-date",
  "July 4, 2026",
  "--audience",
  "general technical viewers",
  "--duration",
  "6.0",
  "--fps",
  "6",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "Three event sources enter one intake contract.",
  "--fact",
  "Queue pressure is the visible bottleneck before worker saturation.",
  "--fact",
  "Retry policy must branch separately from dead-letter inspection.",
  "--fact",
  "Feedback throttle reduces intake only after queue pressure rises.",
  "--fact",
  "The final state must show output continuing after throttling.",
  "--anchor",
  "square intake cells",
  "--anchor",
  "event bus",
  "--anchor",
  "bounded queue",
  "--anchor",
  "worker pool",
  "--anchor",
  "retry branch",
  "--anchor",
  "dead-letter branch",
  "--anchor",
  "feedback throttle gate",
  "--anchor",
  "output stream",
  "--system-label",
  "source A",
  "--system-label",
  "source B",
  "--system-label",
  "source C",
  "--system-label",
  "event bus",
  "--system-label",
  "bounded queue",
  "--system-label",
  "worker pool",
  "--system-label",
  "output stream",
  "--system-label",
  "retry control",
  "--system-label",
  "dead-letter inspection",
  "--system-label",
  "queue pressure metric",
  "--system-label",
  "feedback throttle gate"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
