#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-a-harness-hook",
  "--title",
  "What is a Harness Hook",
  "--topic",
  "What is a Harness Hook",
  "--output-id",
  "what-is-a-harness-hook",
  "--pattern",
  "state-machine",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A harness hook is an active interception point in the runtime lifecycle.",
  "--fact",
  "Hooks run custom logic when an important runtime event occurs.",
  "--fact",
  "Hooks are active guardrails because they run during execution, not only before a session begins.",
  "--fact",
  "GitHub Copilot hooks can execute external commands at lifecycle points like session start, prompt submit, tool calls, and agent stop.",
  "--fact",
  "Claude Code hooks can be shell commands, HTTP endpoints, or LLM prompts.",
  "--fact",
  "OpenCode exposes comparable event-driven control through plugin events.",
  "--fact",
  "Typical hook jobs include formatting, validation, secret protection, audit logging, notifications, and narrowing huge data before the model sees it.",
  "--fact",
  "Hooks can lower cost by preprocessing and shrinking context, but they can raise latency or cost if they trigger slow services too often.",
  "--anchor",
  "event timeline",
  "--anchor",
  "lifecycle pulse",
  "--anchor",
  "shield gate overlay",
  "--anchor",
  "pre-tool checkpoint",
  "--anchor",
  "post-tool checkpoint",
  "--anchor",
  "permission request",
  "--anchor",
  "session start",
  "--anchor",
  "agent stop",
  "--anchor",
  "command block",
  "--anchor",
  "context shrinking counter",
  "--anchor",
  "cost versus latency slider",
  "--state-label",
  "Event",
  "--state-label",
  "Precheck",
  "--state-label",
  "Command",
  "--state-label",
  "Result",
  "--state-label",
  "Postcheck",
  "--state-label",
  "done",
  "--guard-label",
  "Policy",
  "--guard-label",
  "Pre-hook",
  "--guard-label",
  "Post-hook",
  "--guard-label",
  "Allow",
  "--guard-label",
  "Ask",
  "--guard-label",
  "Deny",
  "--guard-label",
  "Session start",
  "--guard-label",
  "Prompt submit",
  "--guard-label",
  "Tool call",
  "--guard-label",
  "Agent stop",
  "--guard-label",
  "Audit log",
  "--guard-label",
  "Context filter"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
