#!/usr/bin/env node
import { spawnSync } from "node:child_process";

const args = [
  "run",
  "--script",
  "skills/html-d3-anime-video-workflow/scripts/build_standalone_explainer.py",
  "--project-root",
  "projects/metro-ai-concept-videos/what-is-a-harness",
  "--title",
  "What is a Harness",
  "--topic",
  "What is a Harness",
  "--output-id",
  "what-is-a-harness",
  "--pattern",
  "layered-architecture",
  "--checked-date",
  "2026-07-04",
  "--audience",
  "general technical viewers",
  "--duration",
  "120.0",
  "--fps",
  "30",
  "--width",
  "1280",
  "--height",
  "720",
  "--edge-style",
  "square",
  "--fact",
  "A harness is the runtime wrapper that turns a raw model into a usable assistant or agent.",
  "--fact",
  "A harness defines instruction layers, default tools, permissions, model picker, execution loop, approvals, memory behavior, logging, and extensibility surface.",
  "--fact",
  "The model is like the engine; the harness provides steering, brakes, dashboard, and controls.",
  "--fact",
  "Different harnesses feel different even when they can call the same model.",
  "--fact",
  "GitHub Copilot emphasizes GitHub-native workflows and explicit AI-credit accounting.",
  "--fact",
  "Claude Code emphasizes skills, hooks, MCP, and coding autonomy.",
  "--fact",
  "OpenCode emphasizes openness and provider choice.",
  "--fact",
  "Harness defaults affect quality, latency, cost, and risk because they change tools, context, retries, and autonomous loops.",
  "--anchor",
  "comparison grid",
  "--anchor",
  "runtime stack",
  "--anchor",
  "model engine",
  "--anchor",
  "steering controls",
  "--anchor",
  "instruction layers",
  "--anchor",
  "default tools",
  "--anchor",
  "permission gate",
  "--anchor",
  "approval control",
  "--anchor",
  "logging surface",
  "--anchor",
  "cost meter",
  "--anchor",
  "use-case matrix",
  "--layer-label",
  "User",
  "--layer-label",
  "Instructions",
  "--layer-label",
  "Model",
  "--layer-label",
  "Tools",
  "--layer-label",
  "Files / shell",
  "--layer-label",
  "Approvals",
  "--concern-label",
  "Logging",
  "--concern-label",
  "Memory rules",
  "--concern-label",
  "Execution loop",
  "--concern-label",
  "Permissions",
  "--concern-label",
  "GitHub workflow",
  "--concern-label",
  "Skills / hooks / MCP",
  "--concern-label",
  "Provider choice",
  "--concern-label",
  "Cost and risk"
];
const result = spawnSync("uv", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
